<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve_Approvals</name>
   <tag></tag>
   <elementGuidId>8e20c4ef-59e5-424c-8981-509057813129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='centresServicesMainDT']/tbody/tr/td[5]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-button.btn-only-icon.btn-success.approve-centres-services-main-button.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a9b553e-3d02-4ebd-a0f5-8809168897a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f01d9332-6e8c-4902-a79c-ea8c3ed27b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>a9634e72-ba38-41f1-8251-93ddab882697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button btn-only-icon btn-success approve-centres-services-main-button mr-1</value>
      <webElementGuid>7c149599-7670-4d7a-8a4a-cc9748aefc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#approve-centres-services-main-modal</value>
      <webElementGuid>b9d6dc96-444b-41f3-bc04-60b37876b588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>7f110293-846e-40b1-b83d-b5a49c5dc340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip514828</value>
      <webElementGuid>14ac1c9a-b5e4-4c68-a3f7-efeab05bbacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centresServicesMainDT&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;p-3 sorting_2&quot;]/button[@class=&quot;mat-button btn-only-icon btn-success approve-centres-services-main-button mr-1&quot;]</value>
      <webElementGuid>fe2ac92f-0ee2-46a6-a566-f3430e9c56b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='centresServicesMainDT']/tbody/tr/td[5]/button</value>
      <webElementGuid>b50598d6-2ba3-4989-8097-639f5badc1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Data'])[1]/following::button[1]</value>
      <webElementGuid>049058dc-4707-4f84-bf27-2b425e35f56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Final'])[1]/following::button[2]</value>
      <webElementGuid>6a864bf7-b5c0-4bac-acf4-16d31c931de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::button[2]</value>
      <webElementGuid>ae206e71-5de6-4bf7-8fc0-5d73bea05bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button</value>
      <webElementGuid>40be31d1-767e-49f5-9642-51335f3d6774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
