<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>c1fb5fb7-b8ff-4e27-80a5-5dba625d936e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-light.rounded-0.border.mb-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d83d680d-36dc-414a-a706-c8c49b5ae0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>rest/auth/end-session</value>
      <webElementGuid>30e85b19-2b05-4023-934b-f6a599d30872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light rounded-0 border mb-0</value>
      <webElementGuid>aa0fcf29-7626-41ad-8c9b-6042323a0255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>202df243-e8f2-4f23-be1b-7f8465a736bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ic-cms body-open-menu&quot;]/header[@class=&quot;topbar box-shadow-card z-index-1&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;dropdown mr-4 mt-2 show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right p-0 show&quot;]/div[@class=&quot;dropdown-item border-top py-2 bg-light text-center&quot;]/a[@class=&quot;btn btn-light rounded-0 border mb-0&quot;]</value>
      <webElementGuid>cfeead68-de3b-44f7-b45e-3d1bd417953b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>c5762464-fb25-4d0c-ba8b-6b288f15901d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/following::a[1]</value>
      <webElementGuid>ddfa6966-d766-4cf9-a496-17adb9efbd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STRUCTURED DATA MANAGEMENT SYSTEM'])[1]/following::a[2]</value>
      <webElementGuid>02605c14-3a3d-41b3-a572-b0f4d50aeb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[1]</value>
      <webElementGuid>103a0563-17b2-4877-bb0c-e46a00e8c8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Structured Data'])[1]/preceding::a[2]</value>
      <webElementGuid>8f572d0b-fe22-4c90-8126-e1833a309e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>cacffc65-8bdf-4927-b292-9c498d7ab7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'rest/auth/end-session')]</value>
      <webElementGuid>64712758-ddaa-4291-83fb-1f43269543c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>6998fcd0-9d4e-4ec5-b630-33c1373a0006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'rest/auth/end-session' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>7b303abe-2445-403e-bd9f-4b92d8cb7c46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
