<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tittle_Home</name>
   <tag></tag>
   <elementGuidId>30ed0b24-21a1-45de-ae83-691036005e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='index-page-app']/div/header/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>f03a3624-4e7c-46b7-b843-482e16e75772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>e0ea010f-d3d7-49a9-9021-02c15f237418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-page-app&quot;)/div[@class=&quot;container-fluid&quot;]/header[@class=&quot;header pt-4 px-4 d-flex align-items-center justify-content-between&quot;]/h3[1]</value>
      <webElementGuid>4b19d256-4223-4b49-b569-583ae8d6db9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='index-page-app']/div/header/h3</value>
      <webElementGuid>2987a0f4-5ed9-43af-afeb-027aef74244b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::h3[1]</value>
      <webElementGuid>6ba3ba3e-0af7-4e8f-a255-c403c40b6ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedure'])[1]/following::h3[1]</value>
      <webElementGuid>3bd96e17-2d44-4cb0-b9e7-3d01fdcfa28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Structured Data'])[2]/preceding::h3[1]</value>
      <webElementGuid>4ad53fd6-d0c0-4208-8172-e7e1d554fbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinic'])[3]/preceding::h3[1]</value>
      <webElementGuid>3157207d-ec0e-41f8-a863-573073e9cf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>3bf8f3d5-e9d1-47d2-8ea2-0b1eaeb29293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>58ee4798-c106-42b4-819c-a83b9ff3f1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
