<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Pick assets using the Frontify Finder_I_155f5e</name>
   <tag></tag>
   <elementGuidId>a1d0d374-7386-4f7f-9dc3-3f78f0b9b0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontify'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg[name=&quot;IconCheckMarkCircle24Filled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e942d3b8-0b26-4867-bd81-163ba0b9e121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>5b2bb293-cd3c-40a8-b272-002bd1cbcdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d11e2a04-5dca-4682-9964-829cc1f9bc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>237c9b97-89b3-4669-af27-e85abf4be887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-items-center tw-justify-center tw-fill-current</value>
      <webElementGuid>48b67a1f-2f25-4890-b7f4-5861d1676260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IconCheckMarkCircle24Filled</value>
      <webElementGuid>274684c7-1d44-40a8-99a8-0099cfbffd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f9fc209-98c5-40c5-8271-68c5e8b5dc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mod modLayout skinLayoutAuth&quot;]/body[@class=&quot;oauth-authorize__body&quot;]/div[@class=&quot;mod mod-oauth-authorize oauth-authorize&quot;]/div[@class=&quot;oauth-authorize__scrollable-blocks&quot;]/div[@class=&quot;oauth-authorize__block oauth-authorize__block--darker&quot;]/div[@class=&quot;oauth-authorize__block-content&quot;]/ul[1]/li[@class=&quot;oauth-authorize__scope&quot;]/span[@class=&quot;ca-icon ca-icon--lg oauth-authorize__scope-icon&quot;]/span[1]/svg[@class=&quot;tw-flex tw-items-center tw-justify-center tw-fill-current&quot;]</value>
      <webElementGuid>8a9a2631-a882-4023-b204-94b0255ba558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontify'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>2f4a220c-234e-49eb-b539-0a9c0818239a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow access'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>0ed7ad4d-3349-4d22-ac37-f0ec7dabb39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@name = 'IconCheckMarkCircle24Filled']</value>
      <webElementGuid>ec98194d-fcf5-4122-8139-803ea47c5705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
