<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Abdul Razakjr Bin Omar</name>
   <tag></tag>
   <elementGuidId>927d3d81-88fd-46b3-8510-ca3262773c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b053344-e329-48ce-99c7-54d789e28ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>71300547-1bc8-4f66-8dc6-55be0aefd631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>113c49d5-e208-4d6e-a80e-f54cf65505e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-1-0</value>
      <webElementGuid>c512700c-5e1f-4f5d-abe6-fddeccc335fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>654faab2-4215-4f89-a6ff-6a3d17719fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e1ff2ad-8923-48a2-bdd1-833cdcdfe2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1201</value>
      <webElementGuid>26d70dfb-6970-4078-a0ba-573d46e3a6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0f9c5e17-77d7-4423-9359-fb6f2b57413a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abdul Razakjr Bin Omar</value>
      <webElementGuid>5cba382a-5585-4bf2-b36b-6c8cef5d2e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-0&quot;)</value>
      <webElementGuid>6a34787d-1344-4873-937f-6ccac85ef3db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-0']</value>
      <webElementGuid>6a43d33e-8fcd-4b42-9be1-b7d0ef3bf550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-1']/ul/li/a</value>
      <webElementGuid>d9dced0a-84fb-4c25-8f31-d78077937621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[3]/following::a[1]</value>
      <webElementGuid>7bfba376-595d-4afd-8202-e5ef2d0646f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[3]/following::a[1]</value>
      <webElementGuid>012a103f-c4ff-4d8f-9c99-9ff6195980b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adrian Siew Ming Saurajen'])[2]/preceding::a[1]</value>
      <webElementGuid>3db3a9c9-4cb9-4f9c-a11a-21698c5e1e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/ul/li/a</value>
      <webElementGuid>f52c6d0b-0f12-4c6a-bcbd-d9e441a46d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-1-0' and (text() = 'Abdul Razakjr Bin Omar' or . = 'Abdul Razakjr Bin Omar')]</value>
      <webElementGuid>8c4758e0-4aa9-4da7-ba95-82f59276b743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
