<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adrian Siew Ming Saurajen_Edit</name>
   <tag></tag>
   <elementGuidId>d6c64583-9d81-4774-baec-4d7c9b682fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-3-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-3-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45d1e726-dd03-487d-91bc-636eb92e61e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d629fc66-a609-42a9-8991-3b31ec49848f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>d1e2f5c5-d1dd-4437-95be-fc02ba86092c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-3-3</value>
      <webElementGuid>634d951a-af7c-4480-9bcf-53a7d48d250a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e320a4b1-e1ff-438f-b8a4-1699f281ff42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8988bda3-0c04-47e0-af47-64b8c4860acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1202</value>
      <webElementGuid>5e30a5d1-fd2b-44d2-8c43-9c63e8e4e7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>37c75997-71a8-49a9-bf71-69c6bb8ea508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adrian Siew Ming Saurajen</value>
      <webElementGuid>eea9fae9-3de1-4ffd-97bf-c3a00a951d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-3-3&quot;)</value>
      <webElementGuid>6577b8b0-d5c1-4934-bb3f-d62f6b41819e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-3-3']</value>
      <webElementGuid>c2206c8d-4eae-415b-a338-9190ebbf20ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-3']/ul/li[4]/a</value>
      <webElementGuid>4e572f23-4bbf-415a-8d77-3024521542bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abdul Razakjr Bin Omar'])[3]/following::a[1]</value>
      <webElementGuid>f9bbfbf2-01a6-498c-a505-0b0e31d9d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[3]/following::a[2]</value>
      <webElementGuid>5f078f14-17f4-4ecd-8f16-7315f4cef20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agasthian T'])[2]/preceding::a[1]</value>
      <webElementGuid>9b9f46d0-3f4b-4741-a82e-bf979b38f82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>e2cbb1d0-5202-483e-afca-0956eab51948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-3-3' and (text() = 'Adrian Siew Ming Saurajen' or . = 'Adrian Siew Ming Saurajen')]</value>
      <webElementGuid>26f7aa10-c282-4ee0-ad85-d4353fcc066e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
