<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Meta Data</name>
   <tag></tag>
   <elementGuidId>f1341e67-4273-4188-9932-f7afd7589494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='centres_services_main_modal_add-meta-data-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-meta-data-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c1e099b-f600-43cb-967e-01ed2d81a779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>7dd0d711-bb4c-489f-b4f8-9c1fe3eb80ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-meta-data-tab</value>
      <webElementGuid>2c7605b1-23de-4993-a160-d39d5524c9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-meta-data-tab</value>
      <webElementGuid>469fa428-5153-4696-af6b-fdea7d49292e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>91b713aa-4d78-4e8d-be26-c77b06e00afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#centres_services_main_modal_add-meta-data-tab-content</value>
      <webElementGuid>667bc6f0-1e0d-4701-8636-3fed15d4ed14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c7384240-655b-4066-9a3e-83b2321e5837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>meta-data</value>
      <webElementGuid>a2adf097-fa2f-4407-8135-22ef74463eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b5a6098-9bd4-4b67-baa3-5c337bd53b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meta Data</value>
      <webElementGuid>70dc524b-1bd6-46f0-94fd-a26e99e22901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-meta-data-tab&quot;)</value>
      <webElementGuid>499c028c-2875-4420-8d22-cf39315ff6c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='centres_services_main_modal_add-meta-data-tab']</value>
      <webElementGuid>3c2839ea-7646-46ec-a213-5bb4441c9f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='add-centres-services-main-tab']/li[2]/a</value>
      <webElementGuid>678d983f-ca59-4e0b-aaad-8af538a80c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Meta Data')]</value>
      <webElementGuid>d587d976-dcdf-4fda-94ff-e44231d57dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[1]/following::a[1]</value>
      <webElementGuid>aaa9bdc7-939b-46b7-b644-dc2651395e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Centres &amp; Services (Main)'])[2]/following::a[2]</value>
      <webElementGuid>897ba265-7374-447f-9541-f8f9938b170e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Meta Data']/parent::*</value>
      <webElementGuid>fcc3cc0f-b281-4a49-8d2d-00ac574dc140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#centres_services_main_modal_add-meta-data-tab-content')]</value>
      <webElementGuid>3099775b-c0a3-4990-b66e-1f909c194e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/ul/li[2]/a</value>
      <webElementGuid>db91113c-dca2-4958-a739-4e4f84d56ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'centres_services_main_modal_add-meta-data-tab' and @name = 'centres_services_main_modal_add-meta-data-tab' and @href = '#centres_services_main_modal_add-meta-data-tab-content' and (text() = 'Meta Data' or . = 'Meta Data')]</value>
      <webElementGuid>e5a75104-3a46-4b18-becb-70096a994955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
