<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mount Elizabeth Hospital_Edit</name>
   <tag></tag>
   <elementGuidId>aa24908a-5c3c-4233-8902-5cb4d53278dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-9-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-9-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e251046-1f42-4eab-9a88-15138f037f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>596ff42c-ab44-4232-a771-be860c65b9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>4c0f612d-4e60-4aaf-9dfd-860a3d63ed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-9-3</value>
      <webElementGuid>f2a84817-3ed7-4625-b575-7e7da5afca49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8092e8ca-0cf9-4cbb-a038-25cd13df883f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad8eda68-1f5e-4e28-a75b-b5c1dd33e2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>62321d1f-8593-4f0a-ba8b-96e0bf555170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7d9db8c3-c7ee-45bd-b6bd-0e42c47376d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mount Elizabeth Hospital</value>
      <webElementGuid>5cbc589e-b98e-41b2-a831-966566592153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-9-3&quot;)</value>
      <webElementGuid>be89b2e5-9d39-4cde-a7f2-2c87a71ce663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-9-3']</value>
      <webElementGuid>8ddd4f20-0684-4b80-99d4-71e9ecd29d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-9']/ul/li[4]/a</value>
      <webElementGuid>1a3617ac-06d9-4439-bed3-227d426078e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gleneagles Hospital'])[6]/following::a[1]</value>
      <webElementGuid>1abb2040-4fa7-4dcb-80b8-7517da7819f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/following::a[2]</value>
      <webElementGuid>7f06ef48-7e77-4d49-9af1-6b39a001dd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mount Elizabeth Novena Hospital'])[4]/preceding::a[1]</value>
      <webElementGuid>f110e472-01ab-46da-a52b-ea9b4a68ed45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>c7069001-c47b-425b-aa59-b45075cda373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-9-3' and (text() = 'Mount Elizabeth Hospital' or . = 'Mount Elizabeth Hospital')]</value>
      <webElementGuid>6c4b144f-1104-48ac-bb2f-3de998e5f3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
