<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert-email-already in use</name>
   <tag></tag>
   <elementGuidId>dc10c960-c688-44d4-a470-c0c08f58d07c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-item-url-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='centres_services_main_modal_add-item-url-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>8521d0f4-ecd6-481e-8ca1-827b821dd2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-item-url-error</value>
      <webElementGuid>7a75491a-8bcc-45ab-9e64-91d7db0b0d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-item-url-error</value>
      <webElementGuid>081ecfc8-ad69-43a2-a610-f178a0e0d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger centres-services-main-error-text ml-3 mt-1</value>
      <webElementGuid>f1494f42-35b0-48f9-8f9e-fd92b1cfb2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item URL already in use!</value>
      <webElementGuid>7027e12e-c5c6-4436-8a89-ebf030433d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-item-url-error&quot;)</value>
      <webElementGuid>f84e146f-3c90-41a6-913e-3a010eaf5495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='centres_services_main_modal_add-item-url-error']</value>
      <webElementGuid>29ef15db-66b8-4532-9365-be52d396deeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div[3]/div/small</value>
      <webElementGuid>487004d9-7892-431c-9ac9-cf5c6090a6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::small[1]</value>
      <webElementGuid>517c0dea-3393-4b45-a4f3-a559029e21bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item URL'])[1]/following::small[1]</value>
      <webElementGuid>65b59bc4-2e8a-48c1-903e-4e83edf26d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/preceding::small[1]</value>
      <webElementGuid>feb89589-71a0-4c79-8683-bc1d2fdf6b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::small[1]</value>
      <webElementGuid>16d23c23-5a59-4174-aee2-f913be54dc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Item URL already in use!']/parent::*</value>
      <webElementGuid>2ace8b71-1f5a-45a3-9caf-23014078ac01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/small</value>
      <webElementGuid>cc1e7058-706c-48ce-8169-b8827b87309b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'centres_services_main_modal_add-item-url-error' and @name = 'centres_services_main_modal_add-item-url-error' and (text() = 'Item URL already in use!' or . = 'Item URL already in use!')]</value>
      <webElementGuid>2d6831b2-9704-42b7-82b6-74f31cd278b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
