<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hospital  Gleneagles Hospital_MD</name>
   <tag></tag>
   <elementGuidId>f29ebf67-7bd2-4568-9c77-3e1c7de38d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-button-collapse-meta-data-K3mmT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_add-button-collapse-meta-data-K3mmT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5dc5b04-e86b-4968-882d-0a4b246ab443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btn-block text-left</value>
      <webElementGuid>1dde6d57-2a04-4191-8559-f70fa81b5464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4508c27c-c61a-4697-8ce7-c11e3f3ca077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-button-collapse-meta-data-K3mmT</value>
      <webElementGuid>a3a9a5c5-9a7f-4ca5-9d42-254641015e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-button-collapse-meta-data-K3mmT</value>
      <webElementGuid>7ac2fa13-7e07-4470-9aed-0673f4408fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>c4a85a33-e3b1-49ce-8156-b4cbe835aafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse-K3mmT</value>
      <webElementGuid>802c0ecd-45ac-48f0-b985-702f84bfc058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0952084c-3aff-42bf-be2e-059d6e4b0fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse-K3mmT</value>
      <webElementGuid>e4a04203-3bdb-4b74-9a98-3fe2ec4c78c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hospital : Gleneagles Hospital</value>
      <webElementGuid>5cf70925-832c-4df0-b4dc-fc785ad3e6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-button-collapse-meta-data-K3mmT&quot;)</value>
      <webElementGuid>596604ce-3a55-4c60-b2a7-555c39f0017e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_add-button-collapse-meta-data-K3mmT']</value>
      <webElementGuid>83e1611e-d2ea-4f86-9eb5-534c6b0ab1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading-K3mmT']/span/div/button</value>
      <webElementGuid>74519736-fff3-4fff-9db2-8eacab0fd908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::button[1]</value>
      <webElementGuid>75d697bf-3c9a-4089-90c8-923032480706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Date'])[2]/following::button[1]</value>
      <webElementGuid>3290c109-2b61-4dc0-bd5a-e3e98e7cb8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Main Image'])[1]/preceding::button[1]</value>
      <webElementGuid>8dd3950c-1463-40ab-b48f-bccf57865b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hospital : Gleneagles Hospital']/parent::*</value>
      <webElementGuid>c8d51f57-bb8c-441a-9a8a-dc8789e7357c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/button</value>
      <webElementGuid>14a369bb-b533-40f8-8d9d-4a5fd61ce2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main_modal_add-button-collapse-meta-data-K3mmT' and @name = 'centres_services_main_modal_add-button-collapse-meta-data-K3mmT' and (text() = 'Hospital : Gleneagles Hospital' or . = 'Hospital : Gleneagles Hospital')]</value>
      <webElementGuid>5d01845f-671b-4d35-b27f-36553f0b13e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
