<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nothing selected</name>
   <tag></tag>
   <elementGuidId>e1b5647c-e0f7-4f86-b1de-02db15afa53a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e09d1116-d1a4-48f7-82e5-60840a28d671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default dropdown-toggle</value>
      <webElementGuid>2925827c-7816-456b-b0f6-7a3a00976f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca012d7d-9478-4dc2-9f4b-edfac0b959ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton</value>
      <webElementGuid>e5c50bd5-b2d2-4275-92ea-42380027420e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton</value>
      <webElementGuid>aa3aaf96-3703-44ee-91b3-7e69b0eefc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>a2c13074-966f-4203-bb9d-c82bd307e6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a4841a9-5562-4326-a1c1-e2a0cf323441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aea98241-3482-422f-ab7c-1c8d26347459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nothing selected</value>
      <webElementGuid>aeb29b60-e85a-41b4-8c0e-17893627ebed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton&quot;)</value>
      <webElementGuid>73a1f08a-509a-43b6-be4c-b8c49e0e95f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton']</value>
      <webElementGuid>8e66ecd2-51a4-4d16-aaaa-086eecd4cb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-specialty-checkboxes-container']/button</value>
      <webElementGuid>da56ea16-015c-403f-a129-910139cf1ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specialties'])[1]/following::button[1]</value>
      <webElementGuid>4ad2708b-31d6-4fe2-9249-a9225c23103b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parkway East Hospital'])[2]/following::button[1]</value>
      <webElementGuid>86e30676-0e7d-42fb-b277-8c052cc71589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acute Pain Management'])[1]/preceding::button[1]</value>
      <webElementGuid>ce12d553-9189-47e1-8e3d-439edeff6e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nothing selected']/parent::*</value>
      <webElementGuid>ecf3b385-93f6-4518-86ef-cff7ffbe6273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/button</value>
      <webElementGuid>5524d1d3-e7f0-4230-8b07-fe4e9b52c1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton' and @name = 'centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton' and (text() = 'Nothing selected' or . = 'Nothing selected')]</value>
      <webElementGuid>a96ae9c6-e29e-44d8-8752-44f565d95d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
