<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send For Approval_Send to AP</name>
   <tag></tag>
   <elementGuidId>eaf5bcd6-0c82-4288-a360-efc75a92dc21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_approval-button-send-approval']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_approval-button-send-approval</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb5a3d05-c57d-4aa0-8e2a-d8569d206b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>47ea8a98-6218-4c9a-ba30-01491b54b296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_approval-button-send-approval</value>
      <webElementGuid>4b448e9b-e676-42df-9a61-ad353bdb3343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_approval-button-send-approval</value>
      <webElementGuid>14be6700-88ef-4985-b1b4-ffefa36544bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mat-button btn-success</value>
      <webElementGuid>80de0936-aca4-478b-b43e-316af65e635c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Send For Approval
                                                </value>
      <webElementGuid>56eb6bf4-8700-4346-8b00-bdc9423c5452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_approval-button-send-approval&quot;)</value>
      <webElementGuid>87a151a6-f0a4-48b6-9f32-b6a6f337eb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_approval-button-send-approval']</value>
      <webElementGuid>d877b03e-9de9-4a95-a000-d11c0b605b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='send-approval-centres-services-main-form']/div[2]/button</value>
      <webElementGuid>0f2e3023-9edb-45cb-b3c9-ea7dcccca374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpublish Centres &amp; Services (Main)'])[1]/preceding::button[1]</value>
      <webElementGuid>d60fdaf8-92e4-433d-ad08-ddc990d08a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/form/div[2]/button</value>
      <webElementGuid>9fc3259a-97a2-4332-b1b2-823f8ea0395a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'centres_services_main_modal_approval-button-send-approval' and @name = 'centres_services_main_modal_approval-button-send-approval' and (text() = '
                                                    Send For Approval
                                                ' or . = '
                                                    Send For Approval
                                                ')]</value>
      <webElementGuid>f98f81fa-468e-4e38-b933-cf215891cae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
