<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Draft_Delete</name>
   <tag></tag>
   <elementGuidId>577a8d7d-b96f-4270-9568-452647e2a6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main-button-delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main-button-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b537b9a-c6cf-4b87-a8d7-67abcaa799a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf7069db-907e-4891-b35e-639f5ccaff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button btn-only-icon btn-danger delete-centres-services-main-button</value>
      <webElementGuid>7dede43a-2a41-40d9-aef2-01f92eab9de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main-button-delete</value>
      <webElementGuid>12622b3d-ebaa-4f68-8686-4f1432384ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main-button-delete</value>
      <webElementGuid>6478f4a1-d24b-4873-b9b5-48d84bd84167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>862c6bb3-641a-4285-a706-3e0e9efeb98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#delete-centres-services-main-modal</value>
      <webElementGuid>01b1e374-ef4d-47a5-917d-ea6e34073cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main-button-delete&quot;)</value>
      <webElementGuid>1d876156-1f1f-4806-baf1-cba71e45e484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main-button-delete']</value>
      <webElementGuid>8a51645f-f9bf-423b-853e-300ff0d4e5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='centresServicesMainDT']/tbody/tr/td[6]/span[2]/button</value>
      <webElementGuid>92171766-c497-40fd-b9d8-d7ebf92a04b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::button[3]</value>
      <webElementGuid>4e7ae484-bbc5-438e-b7ee-81cc021213e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Edit'])[1]/following::button[3]</value>
      <webElementGuid>c2a8a5a1-594b-4bc4-b853-eba4fb458ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 18 total entries)'])[1]/preceding::button[1]</value>
      <webElementGuid>fb6ebeda-5f73-4067-b097-5d910a9aef13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>52d5b310-8ee9-487b-b6a5-3b314bf469e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main-button-delete' and @name = 'centres_services_main-button-delete']</value>
      <webElementGuid>47fd89d1-67c6-4b59-a6d9-394c4a8cf446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 16 total entries)'])[1]/preceding::button[1]</value>
      <webElementGuid>1a813b4b-543d-4fb0-bbec-4d061c9d4dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test CS'])[1]/preceding::button[1]</value>
      <webElementGuid>68d074f9-9027-440d-87f9-3a99c51f9407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::button[1]</value>
      <webElementGuid>4ec57bc9-76f8-482d-bfa8-f277310c66e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
