<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>06ac1d1d-91ae-4acf-827d-b2bf68e6975a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='delete-centres-services-main-form']/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-footer.px-2 > button.btn.mat-button.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15cf9060-65d0-4be9-abe4-99e53e689fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mat-button btn-danger</value>
      <webElementGuid>95bd2183-1a2f-4dec-8174-c8c000f42e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Delete
                                                </value>
      <webElementGuid>854ecbc5-1abc-44df-956d-80a1e748e84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-centres-services-main-form&quot;)/div[@class=&quot;modal-footer px-2&quot;]/button[@class=&quot;btn mat-button btn-danger&quot;]</value>
      <webElementGuid>04e445a4-d72f-46e3-a89c-164c34ff9e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='delete-centres-services-main-form']/div[2]/button</value>
      <webElementGuid>2b8a4fc9-277f-4775-857a-d111363f5c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Edit'])[2]/following::button[1]</value>
      <webElementGuid>4d67d302-4373-416a-9449-3225765aa46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please confirm deletion of Centres &amp; Services (Main)'])[1]/following::button[1]</value>
      <webElementGuid>b699e71c-4c3c-4c1f-90e4-cd5360bad167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>78e345f6-8bd6-4e03-bf22-f75289eb1bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/form/div[2]/button</value>
      <webElementGuid>813823f3-da79-496b-80df-dc6abf0e4182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                                    Delete
                                                ' or . = '
                                                    Delete
                                                ')]</value>
      <webElementGuid>a5f71617-f922-41e7-86b5-e8202db2cc80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
