<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unpublish</name>
   <tag></tag>
   <elementGuidId>ac6b5aaa-87f0-40af-a63f-415c3e7218cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_unpublish-button-unpublish']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_unpublish-button-unpublish</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39a8ffc3-529d-4ddc-8f10-463cc0662dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mat-button btn-secondary</value>
      <webElementGuid>63b6c0c3-4f7d-42cd-956b-632d8488d98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_unpublish-button-unpublish</value>
      <webElementGuid>3be28ec5-591d-46c8-a198-d0cc75237c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_unpublish-button-unpublish</value>
      <webElementGuid>a122bb07-00c2-4367-a084-e4205a28363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Unpublish
                                                </value>
      <webElementGuid>1d201991-b0c1-4c74-9251-b041d1d31f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_unpublish-button-unpublish&quot;)</value>
      <webElementGuid>2bdf9578-3df1-4f9a-9820-ebea7d59ff58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_unpublish-button-unpublish']</value>
      <webElementGuid>f8bf4e86-9ea1-4399-b616-b570ea3e4bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='unpublish-centres-services-main-form']/div[2]/button</value>
      <webElementGuid>92b0a1b2-1a7e-4f21-ade8-67ae95bf8bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Edit'])[2]/following::button[1]</value>
      <webElementGuid>e468a49d-9135-4608-aea2-cec30a9caac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/form/div[2]/button</value>
      <webElementGuid>68ac1dfa-d592-46dd-81ae-dde54adae4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'centres_services_main_modal_unpublish-button-unpublish' and @name = 'centres_services_main_modal_unpublish-button-unpublish' and (text() = '
                                                    Unpublish
                                                ' or . = '
                                                    Unpublish
                                                ')]</value>
      <webElementGuid>687bc913-3cd8-4fb5-b8f8-d1274ef5aa11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
