<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New Revision</name>
   <tag></tag>
   <elementGuidId>70483904-0883-4e7b-8b39-c0b79d3d67c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_new_revision-button-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_new_revision-button-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7868a28d-e7c3-4a2b-bd11-abfb10ecec95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1b6bbb37-7b94-48ef-9ec3-75fefe006a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mat-button btn-orange</value>
      <webElementGuid>63865868-b079-4fb8-a5ed-e1f9b479b419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_new_revision-button-submit</value>
      <webElementGuid>d77488ee-65b7-4688-bf1e-a2d87ad2a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_new_revision-button-submit</value>
      <webElementGuid>6d4513cf-9183-40b7-b02b-b91f54ef0ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    New Revision
                                                </value>
      <webElementGuid>fa3b8c94-ac1d-4f61-9a1f-db9e2686689c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_new_revision-button-submit&quot;)</value>
      <webElementGuid>33f829f8-4d9c-41ae-bcec-551597a51840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_new_revision-button-submit']</value>
      <webElementGuid>c9131a9e-14f2-417c-a5f1-14d539a0d95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new-revision-centres-services-main-form']/div[2]/button</value>
      <webElementGuid>6414d819-e880-470b-ab8a-bfd46c847d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please confirm the creation of new revision?'])[1]/following::button[1]</value>
      <webElementGuid>093f10c9-0858-4a9a-94a1-ae8bbc746b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centres &amp; Services (Main) Revision'])[1]/following::button[2]</value>
      <webElementGuid>1229fcc2-306a-4484-bc8b-5ec22c671f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::button[1]</value>
      <webElementGuid>0167a51c-62fb-4fcb-9a47-f37a24d30b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/form/div[2]/button</value>
      <webElementGuid>abfcc81f-71c4-4a0a-a832-bb4021be2151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'centres_services_main_modal_new_revision-button-submit' and @name = 'centres_services_main_modal_new_revision-button-submit' and (text() = '
                                                    New Revision
                                                ' or . = '
                                                    New Revision
                                                ')]</value>
      <webElementGuid>e06275b3-e321-445c-93cd-2f7b8958499a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
