<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_close_Detail-page</name>
   <tag></tag>
   <elementGuidId>3933cf16-308d-46d3-813c-e81235b83408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_translate-button-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_translate-button-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73548cbb-d15f-4814-ae1c-0465ce54b11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01064a21-0b3e-4099-833c-b2e267169ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>07fc6b86-abba-479d-ae19-41bcfde57d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_translate-button-close</value>
      <webElementGuid>884e6eff-4cdc-4e14-9366-ef3aeb432fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_translate-button-close</value>
      <webElementGuid>acec6ccc-bbd8-4495-9c98-ed8120e03e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b2f4171f-e528-4ffc-aecc-0dc878995a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>68e5bd22-1f9f-4f51-be79-ffb79a830815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    ×
                </value>
      <webElementGuid>ffbec632-a2a2-4878-b177-80607f6727db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_translate-button-close&quot;)</value>
      <webElementGuid>a2652c0e-b478-4aad-bdce-102baefa6c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_translate-button-close']</value>
      <webElementGuid>0fe89d64-b1ae-420a-aa0b-8a519f1fee62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_translate']/div/div/div[2]/button</value>
      <webElementGuid>e0aa128b-6bfb-4598-a2ff-cfd470bbb8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centres &amp; Services (Main)'])[5]/following::button[1]</value>
      <webElementGuid>6f3d7ea4-ac39-497b-bdcf-861a489e62e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sending item for translation'])[1]/following::button[1]</value>
      <webElementGuid>419e93e2-2537-4656-9f36-48f74ca457cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[3]/preceding::button[1]</value>
      <webElementGuid>fe0c5e8a-bbb8-4115-aebd-2cff48338eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Data'])[3]/preceding::button[1]</value>
      <webElementGuid>09961d26-7fab-48ce-8210-5510a8687ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/button</value>
      <webElementGuid>835b39e2-6244-4011-9be0-db9c65150a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main_modal_translate-button-close' and @name = 'centres_services_main_modal_translate-button-close' and (text() = '
                    ×
                ' or . = '
                    ×
                ')]</value>
      <webElementGuid>de65e676-478a-4891-b7a6-78e88905a84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
