<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nothing selected_1</name>
   <tag></tag>
   <elementGuidId>b48a60e6-82df-4a07-8e19-986cb050550c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[45]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.bootstrap-select.show-tick.dynamic-picker.service-provider-types-select.ignore-trigger > button.btn.dropdown-toggle.btn-light.bs-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f266e65-ed88-427d-bc36-9a374b97453e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7e36cd5-6921-46ec-9aad-7c2830bc44ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle btn-light bs-placeholder</value>
      <webElementGuid>dd6b6ddf-9230-4c78-92d4-c08231250546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>eace0ddb-fcdd-4327-9f17-849ecbda0037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>bfc824d1-4eda-48c0-840d-966ac348ae3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>bs-select-8</value>
      <webElementGuid>a324fa12-36d6-4b83-9efd-0d9fa3cc64a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5b5a3886-c1f6-48ce-b4c7-5830aba223c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1f442b2-a8ad-42be-bde5-c9226da7d325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-select-service-provider-types</value>
      <webElementGuid>b9b2fe78-9627-458a-9c6e-97fd6aca55a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nothing selected</value>
      <webElementGuid>4136e492-6091-4396-9deb-345532c99bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nothing selected </value>
      <webElementGuid>39802019-1d98-417d-8710-353c5254782e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-basic-information-tab-content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-xs-6&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-12 col-xs-12 form-container&quot;]/div[@class=&quot;dropdown bootstrap-select show-tick dynamic-picker service-provider-types-select ignore-trigger&quot;]/button[@class=&quot;btn dropdown-toggle btn-light bs-placeholder&quot;]</value>
      <webElementGuid>bcb7bdce-3b3b-41d4-a86a-50c11573a587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[45]</value>
      <webElementGuid>70665069-2f17-4f65-821f-b1559394176d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div[2]/div[3]/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>f8fe1c05-a35c-44b6-a0a3-90307aac475f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Provider Types'])[3]/following::button[1]</value>
      <webElementGuid>b69be2e3-23b9-4606-9fde-93a3c4ebdf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/following::button[1]</value>
      <webElementGuid>085a7c55-7b2f-4043-8e43-a4e294239132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::button[1]</value>
      <webElementGuid>1c15da11-0daa-42bb-b4c6-df64b7358a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>582e1373-34d9-4031-a5d4-95d5db70d729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Nothing selected' and (text() = 'Nothing selected ' or . = 'Nothing selected ')]</value>
      <webElementGuid>3a83cb3d-e1dc-4658-8d5b-0312b467427f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
