<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selected 2 specialties_Edit</name>
   <tag></tag>
   <elementGuidId>2407949a-f723-4877-a1ec-a3c87c312595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd4694cb-3150-4637-ad32-da4128f4a58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default dropdown-toggle has-selected-value</value>
      <webElementGuid>3d7a8828-4a80-49ad-969c-56ea5c44d53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1921da4c-fed7-414d-abfa-3e3f50d1aaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton</value>
      <webElementGuid>4eba1fa8-eec9-40c3-95e0-7973a9d0888d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton</value>
      <webElementGuid>89bdd286-dd20-47a4-8f55-89794030678f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>54d6d86d-a768-483f-81d6-11457210f2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>563c29c7-6148-496e-bd24-acd70af6bb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a11dc19-2ee1-4312-a8cf-9437ee17dd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selected 2 specialties</value>
      <webElementGuid>b7e5b842-e40a-404f-baef-27867e0c79d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton&quot;)</value>
      <webElementGuid>92fd579f-725c-4291-8eeb-90f4f9427e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton']</value>
      <webElementGuid>fb2baadf-6df1-4685-b0d3-7e40847e52ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-specialty-checkboxes-container']/button</value>
      <webElementGuid>59d359c1-6aab-4806-a11d-1c4f6fba08c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specialties'])[2]/following::button[1]</value>
      <webElementGuid>31c81675-5a56-46eb-a17b-c299985fd45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parkway East Hospital'])[4]/following::button[1]</value>
      <webElementGuid>2f8181b6-1a1f-4764-ba19-7e4404466e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acute Pain Management'])[2]/preceding::button[1]</value>
      <webElementGuid>93360443-20f3-40c0-8199-2cca92b9798d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selected 2 specialties']/parent::*</value>
      <webElementGuid>4b169b08-0ad7-47bc-b051-70c87d057d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div[2]/div[3]/div[2]/div/div/div/div/button</value>
      <webElementGuid>1bf3983d-7fa1-4c8d-89b0-96fc87ad305f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton' and @name = 'centres_services_main_modal_edit-specialty-checkboxes-dropdownMenuButton' and (text() = 'Selected 2 specialties' or . = 'Selected 2 specialties')]</value>
      <webElementGuid>cd56f260-2f62-46a0-86fa-cf92dd6e3240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
