<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Copy</name>
   <tag></tag>
   <elementGuidId>a098ebc6-2b47-41e6-96d2-14a5a16ded9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main-button-copy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main-button-copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a7708af-49f7-4c1a-8d25-bbed57fdfa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary buttons-copy buttons-html5 mat-button mx-0 mb-3</value>
      <webElementGuid>fec09be0-3cd9-42f6-8299-47165e1ef5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b83b428-9e38-43d8-921d-1da09acad56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>centresServicesMainDT</value>
      <webElementGuid>33c4a111-a69e-465e-8944-55acb818d8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ad1cf6c-ea27-4d4d-ba9b-f9683d4badfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>cf7fcb16-39fa-45ec-9c46-b4ff60d7e6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main-button-copy</value>
      <webElementGuid>23a423ef-e6e5-4b9a-b5ad-f4d04e8c0e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main-button-copy</value>
      <webElementGuid>952a489d-4d51-4821-aaa5-20915904c57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>ebbc3502-73f4-4d03-99c2-7be7e4d78c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main-button-copy&quot;)</value>
      <webElementGuid>c7a038f5-6898-43d9-bea7-2018837c3039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main-button-copy']</value>
      <webElementGuid>652c40ac-3138-4d94-910d-d14937fffbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exportButtonsContainer']/div/button</value>
      <webElementGuid>19524f7e-241d-4848-b0d5-54540ceaf076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Languages'])[1]/following::button[1]</value>
      <webElementGuid>0d125372-35a4-478f-b97f-e6d3061af5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[1]/preceding::button[1]</value>
      <webElementGuid>7cdafa44-2d33-44ff-a664-7934b356da85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>cc261a65-bf1e-47bc-b13a-db48373ad222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Copy' and @id = 'centres_services_main-button-copy' and @name = 'centres_services_main-button-copy' and (text() = 'Copy' or . = 'Copy')]</value>
      <webElementGuid>41bd5de8-64ba-4bf6-a899-c9038aca3ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
