<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UnPublished</name>
   <tag></tag>
   <elementGuidId>c4443d9a-b849-4fc4-8c84-93353f973d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='centres_services_main-button-unpublish'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8052102-02ad-4dff-95a2-d4afb1dbae42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9cb55e0-7e57-4f90-9e30-b7c80f8d2521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button btn-only-icon btn-secondary unpublish-centres-services-main-button</value>
      <webElementGuid>59c40af9-885c-47a8-9c5d-51658ad21ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main-button-unpublish</value>
      <webElementGuid>e1d7454e-a14a-421b-abce-4026902a993f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main-button-unpublish</value>
      <webElementGuid>95f755e7-dc9d-435c-a461-273735c341d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>2f5deb58-7f65-4889-873a-541f085eb8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#centres_services_main_modal_unpublish</value>
      <webElementGuid>d7ea204a-ca40-4c15-b423-5b130b1139b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centresServicesMainDT&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[6]/span[@class=&quot;d-inline-block&quot;]/button[@id=&quot;centres_services_main-button-unpublish&quot;]</value>
      <webElementGuid>0d73e42c-2b58-4a84-a88e-3b88a877aa67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='centres_services_main-button-unpublish'])[6]</value>
      <webElementGuid>e750cd15-1b7c-4536-a54c-fa08d6c2ce9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='centresServicesMainDT']/tbody/tr[10]/td[6]/span[2]/button</value>
      <webElementGuid>3ad1f7f4-5dfe-4331-8392-967bdea393b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[8]/following::button[3]</value>
      <webElementGuid>d3e38eb4-8b25-4584-b0e8-3ec8b6258fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Edit'])[1]/following::button[3]</value>
      <webElementGuid>be176ae9-8d9a-4b4d-9929-d95e7bb87b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 16 entries'])[1]/preceding::button[1]</value>
      <webElementGuid>4c638854-09d0-4978-9495-e84193879394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[6]/span[2]/button</value>
      <webElementGuid>7831183b-21e3-4e6e-b70f-e5824834bc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main-button-unpublish' and @name = 'centres_services_main-button-unpublish']</value>
      <webElementGuid>862f70cf-ae66-4e1c-a63f-65f4089b9ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
