<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_Edit</name>
   <tag></tag>
   <elementGuidId>21c5b6e1-c21d-440f-b695-96785dc4aa83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_edit-button-save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-button-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfd0368c-02ec-47b1-9eb3-e09fad31fab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mat-button btn-success iconed-button px-4</value>
      <webElementGuid>9dda1fff-26a5-47e2-95e8-7c1d7488d23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-button-save</value>
      <webElementGuid>241bc0bf-b7b7-4d77-85c3-086efb2bea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-button-save</value>
      <webElementGuid>bdec9802-09d7-4d62-8f77-5430eb08db36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Save
                        </value>
      <webElementGuid>c6804a3c-f09b-455c-bce9-a8385cd7b05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-button-save&quot;)</value>
      <webElementGuid>4a9dc9c2-d87c-49b4-bdb3-6a4661a4895e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_edit-button-save']</value>
      <webElementGuid>d555d302-a3d9-4902-9ba4-346d7cd1e521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit-centres-services-main-form']/div[3]/button</value>
      <webElementGuid>a867e93a-c65c-49c3-914c-9eecb50b26f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[3]/following::button[1]</value>
      <webElementGuid>6f7e488c-d74a-4b01-adb2-6cdef9037028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Meta Data'])[2]/following::button[1]</value>
      <webElementGuid>65f7f79f-a7f8-4449-b38e-075418c19d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Close'])[1]/preceding::button[1]</value>
      <webElementGuid>eb07c6a0-a0a9-4d89-9a3f-061bec94fbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/button</value>
      <webElementGuid>bf080b70-eaea-4c77-8857-710c6d1be357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'centres_services_main_modal_edit-button-save' and @name = 'centres_services_main_modal_edit-button-save' and (text() = '
                            Save
                        ' or . = '
                            Save
                        ')]</value>
      <webElementGuid>a9c9ec3a-cb4b-4da1-9781-300cb1d2ba36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
