<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done_Edit</name>
   <tag></tag>
   <elementGuidId>353650fb-397a-472c-b5c2-2b071451f683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-specialty-checkboxes-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-specialty-checkboxes-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8926072a-ffd9-458c-bbfd-e962772d3de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>fd139fd6-644c-4182-a8b8-53d4289a097e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-specialty-checkboxes-submit</value>
      <webElementGuid>e3ff2a70-5dc4-4392-8e46-aaaf2a2a205d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>6b3de1cb-6b54-4e0c-a1c1-e8ac37a190db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-specialty-checkboxes-submit&quot;)</value>
      <webElementGuid>12f97bf3-86c9-47be-8245-01a9f610835e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-specialty-checkboxes-submit']</value>
      <webElementGuid>eeefbf93-e12f-46cf-a1dc-d449485c47fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-specialty-checkboxes-container']/div/div/div[3]/button</value>
      <webElementGuid>306af78e-fb0c-4096-ab8d-9d4ee898cc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wedge Excision for Bladder Neck Contracture'])[2]/following::button[1]</value>
      <webElementGuid>1cda0d42-a77b-44db-971d-11976aead9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vesicocutaneous Fistula, Closure'])[2]/following::button[1]</value>
      <webElementGuid>53ac64d4-cfe8-4906-9fa5-16ba054d6990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Provider Types'])[4]/preceding::button[1]</value>
      <webElementGuid>6984a971-154d-42f8-8ef8-05fdcce334c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div[2]/div[3]/div[2]/div/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>8442bf01-15cb-443b-81f3-a533c52df8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-specialty-checkboxes-submit' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>d2d2cea8-6c77-4ca9-ae82-e6c9c5c80ce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
