<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>c7417651-29c0-410a-8b90-53d02ca88761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[95]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.daterangepicker.ltr.single.opensright.show-calendar.drop-up > div.drp-buttons > button.cancelBtn.btn.btn-sm.btn-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2566795-78d3-4c97-a491-aea88923c165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancelBtn btn btn-sm btn-default</value>
      <webElementGuid>9cd7ad53-4ed3-4866-ae9d-18832ec666e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b82f012-05b1-4359-9fa2-d11bd8500620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>bc9926b8-4f42-41e4-a270-21ffc58905ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body body-open-menu modal-open&quot;]/div[@class=&quot;daterangepicker ltr single opensright show-calendar drop-up&quot;]/div[@class=&quot;drp-buttons&quot;]/button[@class=&quot;cancelBtn btn btn-sm btn-default&quot;]</value>
      <webElementGuid>f30e6bfc-0e6f-4333-aa4e-b321cc31c0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[95]</value>
      <webElementGuid>472d1cb2-ba39-46d8-b387-136b88e1bce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::button[1]</value>
      <webElementGuid>d30bbc74-b858-4b16-8e2b-42fa71f3ddac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[3]/preceding::button[1]</value>
      <webElementGuid>4f6048b2-0122-4654-8aca-7c6715374ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[4]/button</value>
      <webElementGuid>6a36747d-0865-4f7b-be07-3a62563e52e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>dfec5401-cc34-453c-92d5-19a3ed185e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
