<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Draft_centres_services_main-button-edit</name>
   <tag></tag>
   <elementGuidId>4ece2ceb-4212-4b88-bf3f-a10ae5611f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main-button-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main-button-edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>112ba3ac-9ac5-4231-8117-5a66e5ef6191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2bf6c88-f99b-4523-9004-526c03eb34de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button btn-only-icon btn-warning mr-1 edit-centres-services-main-button</value>
      <webElementGuid>fa5a1fae-9531-49ba-8a44-528de4f3655d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main-button-edit</value>
      <webElementGuid>05509693-087f-4d14-9557-ffff7649df51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main-button-edit</value>
      <webElementGuid>37f48459-e449-4ab1-9064-162edffc9c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>ac3f3ccf-6a97-4e71-8138-d5e840b75fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#centres_services_main_modal_edit</value>
      <webElementGuid>814695ea-d21a-41d2-af89-ac41f90f1751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-backdrop</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>de4ff6ed-f980-43ad-b6cd-0aed05a00521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keyboard</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8f29817-5c55-49b9-a3d1-e3df6ffb35db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centresServicesMainDT&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/span[@class=&quot;d-inline-block&quot;]/button[@id=&quot;centres_services_main-button-edit&quot;]</value>
      <webElementGuid>969025f4-3072-47a9-9a55-0045c50ede64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main-button-edit']</value>
      <webElementGuid>6ed4860a-78df-4cbe-a23c-fa16b1a8afe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='centresServicesMainDT']/tbody/tr/td[6]/span/button</value>
      <webElementGuid>59d055f1-6e91-4cd4-9172-53312a6d74c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::button[2]</value>
      <webElementGuid>b9d7c88a-c536-4130-82cd-d1275215a1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Final'])[1]/following::button[2]</value>
      <webElementGuid>30a27a23-3b07-415b-86bc-8a9899d9f0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dsagvash'])[1]/preceding::button[2]</value>
      <webElementGuid>229c3605-1f82-4f41-8fe9-d9972031bd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::button[2]</value>
      <webElementGuid>b0c89e4d-57a8-44e0-ae80-8874e9ff189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span/button</value>
      <webElementGuid>9f1a5039-0033-4fa0-a09d-a8d198c7726b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main-button-edit' and @name = 'centres_services_main-button-edit']</value>
      <webElementGuid>754e7f6d-d961-42b5-b182-1ba9262cd530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
