<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail-draf</name>
   <tag></tag>
   <elementGuidId>2e092de9-4248-4e63-86c5-14715c6318d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main-button-translation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main-button-translation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73e98931-4f77-48ec-baff-2c8b8383f1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>400a1d57-0909-4d78-b19d-c0bfe688d11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button btn-primary translate-centres-services-main-button d-flex align-items-center</value>
      <webElementGuid>71aa259f-6607-4ab1-a7d3-143f606485c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main-button-translation</value>
      <webElementGuid>429cc4e6-5632-4177-8cf9-b57bdf225ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main-button-translation</value>
      <webElementGuid>69f5a272-e071-4b6f-84ef-f02a7ec5ae68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>847b6828-6671-4b78-aef7-d7502489a24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#centres_services_main_modal_translate</value>
      <webElementGuid>99304ff2-beda-481d-8c24-878c697b52d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centresServicesMainDT&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]/span[@class=&quot;d-inline-block&quot;]/button[@id=&quot;centres_services_main-button-translation&quot;]</value>
      <webElementGuid>8496f031-618c-4a78-9ec9-92d9ec351377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main-button-translation']</value>
      <webElementGuid>fcc00759-bd59-4ec3-b8c3-eeb3a66026d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='centresServicesMainDT']/tbody/tr/td[5]/span/button</value>
      <webElementGuid>2af6af28-e071-4a0d-81f5-5fe50956ebfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::button[1]</value>
      <webElementGuid>cac79972-b15c-4d80-bb36-523c57c646bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test V1 Final'])[1]/following::button[1]</value>
      <webElementGuid>21b0827a-d7a5-41b4-af42-238ee503174e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dsagvash'])[1]/preceding::button[3]</value>
      <webElementGuid>f40f8f81-1fb5-4d84-ac8b-11bbe80000dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::button[3]</value>
      <webElementGuid>18120ec4-9e77-492c-9c54-7dac97502bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>f2c432a4-f1d5-4db2-ba03-4ebfce974644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main-button-translation' and @name = 'centres_services_main-button-translation']</value>
      <webElementGuid>54c38a11-a9a3-41f0-b350-1df4851efc0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
