<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hospital  Gleneagles Hospital</name>
   <tag></tag>
   <elementGuidId>437b859a-9b87-41eb-8707-285ab6235058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_add-button-collapse-meta-data-KLTlN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-button-collapse-meta-data-KLTlN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16ff44ab-7d94-4b63-9d1c-b05456eb20bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btn-block text-left</value>
      <webElementGuid>5e67acaf-b6f0-48bf-8f2d-f78504306cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0ce120a-088e-434f-8de5-d3e0fed142bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-button-collapse-meta-data-KLTlN</value>
      <webElementGuid>b230029f-e4cb-47eb-b4df-37cb05d8638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-button-collapse-meta-data-KLTlN</value>
      <webElementGuid>be1d3602-3832-48e4-83fb-8e0df1277590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>5afa6f91-52a7-43a2-b362-6c06856fb3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse-KLTlN</value>
      <webElementGuid>fb7c7a33-fec9-476b-84b7-a837f68b88c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1550f5d8-cab2-461f-881c-92c2ad71a252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse-KLTlN</value>
      <webElementGuid>d7b25efa-b98f-4c56-a656-0d5c905cc217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hospital : Gleneagles Hospital</value>
      <webElementGuid>f03e00a4-9f7f-4faf-b930-9d89a3736a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-button-collapse-meta-data-KLTlN&quot;)</value>
      <webElementGuid>fc575aec-be3c-4142-97a9-1ba99a0ecb5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_add-button-collapse-meta-data-KLTlN']</value>
      <webElementGuid>5f438fc9-c0a2-4282-bb71-4ef221b189f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading-KLTlN']/span/div/button</value>
      <webElementGuid>5ed81770-f932-4237-b48d-96ccccaf6798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::button[1]</value>
      <webElementGuid>61574d55-e492-4a04-8fd2-186ff23a31bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Date'])[2]/following::button[1]</value>
      <webElementGuid>0a0b7ba4-4fe1-47ea-a1a5-894f99bfb2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Main Image'])[1]/preceding::button[1]</value>
      <webElementGuid>c19a18c3-9e30-49ee-be4c-54e0ad434f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hospital : Gleneagles Hospital']/parent::*</value>
      <webElementGuid>f3d73949-22db-4fd4-997b-60faabd7c249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/button</value>
      <webElementGuid>2aae35d3-8f0e-46d8-996e-861371eb9fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main_modal_add-button-collapse-meta-data-KLTlN' and @name = 'centres_services_main_modal_add-button-collapse-meta-data-KLTlN' and (text() = 'Hospital : Gleneagles Hospital' or . = 'Hospital : Gleneagles Hospital')]</value>
      <webElementGuid>6925a348-a432-48da-9d8a-71bc7b64731b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
