<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nothing selected_By-Speciality</name>
   <tag></tag>
   <elementGuidId>b8806fe5-ede9-4989-9cb4-ecb90a3bb75d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61480cd3-f3e0-423f-829d-700a6debe34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default dropdown-toggle</value>
      <webElementGuid>0bd6503c-dec1-42fb-9007-b1f55fd76188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcc72b5d-712d-46a0-94c9-1f572ea65fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton</value>
      <webElementGuid>2263b8a1-7d9c-4e2a-9733-a4297779d6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton</value>
      <webElementGuid>103c4a74-8469-4c03-a3e0-f50964236057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>048366b1-1724-41a5-9d1c-1b0e9767ac4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a66e122-d33b-406f-9d39-f16bf82be03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>122de54c-5e5a-4186-99e4-87f79cf2d2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nothing selected</value>
      <webElementGuid>dd97bbc2-da32-4145-9087-5f7d8b38c5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton&quot;)</value>
      <webElementGuid>55a42895-c450-498e-ba93-0c3a9afbacbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton']</value>
      <webElementGuid>a31ed7e8-dbec-4944-9a92-f3c74f4f2cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-specialty-checkboxes-container']/button</value>
      <webElementGuid>a5616a70-9feb-4c31-a8fd-a9752e375ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specialties'])[1]/following::button[1]</value>
      <webElementGuid>c3ee71da-e9be-4508-9ca3-540293025920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[1]/following::button[1]</value>
      <webElementGuid>be285a76-f02c-43d0-b740-1adea60d5340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acute Pain Management'])[1]/preceding::button[1]</value>
      <webElementGuid>f17f8dc0-df00-4886-be21-06f8f2a5599b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/button</value>
      <webElementGuid>76b1f22d-31be-46ed-8e3d-0cfd5bad34c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton' and @name = 'centres_services_main_modal_add-specialty-checkboxes-dropdownMenuButton' and (text() = 'Nothing selected' or . = 'Nothing selected')]</value>
      <webElementGuid>39037699-768e-4aa6-bd0a-31132c289299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
