<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pagination</name>
   <tag></tag>
   <elementGuidId>9aca9916-aafa-40a9-9e3e-da49e9990624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='centresServicesMainDT_paginate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centresServicesMainDT_paginate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>336d384f-9fc2-40ce-960b-eb15ffef53c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_paginate paging_simple_numbers</value>
      <webElementGuid>d4577a1a-be0d-4a49-8016-6b076d8d2799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centresServicesMainDT_paginate</value>
      <webElementGuid>f896bb59-1cdd-4769-a9c8-a88c3fcab060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous12Next</value>
      <webElementGuid>d80b9658-f554-44c2-8534-1591ad781c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centresServicesMainDT_paginate&quot;)</value>
      <webElementGuid>76034c52-d931-4610-aef7-65978526d32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='centresServicesMainDT_paginate']</value>
      <webElementGuid>f9009153-4191-4dd9-bc7c-4207172e318c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centresServicesMainDT_wrapper']/div[2]</value>
      <webElementGuid>5e115713-1eee-405a-802f-85bae27bff59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 16 entries'])[1]/following::div[1]</value>
      <webElementGuid>f84e2dcd-8fef-4755-8d5d-0a62bf36048a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[8]/following::div[2]</value>
      <webElementGuid>f4008782-c7a0-44ce-9b8a-3bf7525d6a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[3]</value>
      <webElementGuid>9e797734-509d-4319-bbe2-870c99b2cf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[2]</value>
      <webElementGuid>27795e3d-46d3-4b8c-b8de-65e21b4afb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'centresServicesMainDT_paginate' and (text() = 'Previous12Next' or . = 'Previous12Next')]</value>
      <webElementGuid>c6705c59-b150-420c-ba93-949bce1ad340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[7]/following::div[2]</value>
      <webElementGuid>e3f89bba-6dca-49b7-acc2-943f95e7564f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
