<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Copy CSV Excel PDF Print</name>
   <tag></tag>
   <elementGuidId>c7321fa3-fccb-4a8f-a87d-345493695f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='exportButtonsContainer']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dt-buttons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ff4493f-59da-4b58-a0b6-a08ffcb3fc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-buttons</value>
      <webElementGuid>08ff870d-feb4-4131-b799-dd097f7ab999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>          Copy CSV Excel PDF Print </value>
      <webElementGuid>5d90b310-c1d6-47d5-8675-4647b1f41816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exportButtonsContainer&quot;)/div[@class=&quot;dt-buttons&quot;]</value>
      <webElementGuid>aa8d2545-5e31-4f10-8c6d-22d56bee202f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exportButtonsContainer']/div</value>
      <webElementGuid>3528eae4-fd6f-457a-8b06-3050ae0f67a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Languages'])[1]/following::div[2]</value>
      <webElementGuid>806bcd89-5219-43dc-9dd4-25c94e4d79d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>d3d3e12d-6253-43a6-aa5d-a0a0d6f3b874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '          Copy CSV Excel PDF Print ' or . = '          Copy CSV Excel PDF Print ')]</value>
      <webElementGuid>6b89afcf-b8fc-4573-acff-855674d07031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
