<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Centres  Services (Main)_Pending Publish</name>
   <tag></tag>
   <elementGuidId>2f112a73-62f9-4583-8597-b591b735c554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='translate-centres-services-main-modal-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#translate-centres-services-main-modal-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>b1140985-3a63-44cf-b133-3620a44ebb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>d5bec158-da12-471b-8149-71818d9dd799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>translate-centres-services-main-modal-title</value>
      <webElementGuid>97a8b668-98e3-47c7-bc4d-7d5ad11b9b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Centres &amp; Services (Main)</value>
      <webElementGuid>285c36a2-df3e-4c17-bd83-f457c1b7630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;translate-centres-services-main-modal-title&quot;)</value>
      <webElementGuid>d5aebe2f-8c98-4020-9402-833a8971f967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='translate-centres-services-main-modal-title']</value>
      <webElementGuid>dab4820e-49e1-4c4c-a553-7f67ec87bce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_translate']/div/div/div[2]/h5</value>
      <webElementGuid>32a382ef-016d-45dd-8e09-883727467a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sending item for translation'])[1]/following::h5[1]</value>
      <webElementGuid>c05f5f66-e9f2-4317-8f6c-b975dd766526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Close'])[1]/following::h5[1]</value>
      <webElementGuid>a59b3f56-0cda-43ba-a1b5-3d61f9ac6697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[3]/preceding::h5[1]</value>
      <webElementGuid>15fbe796-80c0-4d11-8b9f-5b04d4c19753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Data'])[3]/preceding::h5[1]</value>
      <webElementGuid>170d890c-8444-4f86-802c-8005d81786ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/h5</value>
      <webElementGuid>d795bc90-2755-478a-b9bb-eb48f8a168f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'translate-centres-services-main-modal-title' and (text() = 'Centres &amp; Services (Main)' or . = 'Centres &amp; Services (Main)')]</value>
      <webElementGuid>bc253d26-d3da-4165-91eb-0003743a1f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
