<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Centres  Services (Main)_Detail</name>
   <tag></tag>
   <elementGuidId>a1eab48f-c30f-4dd0-97d3-c9efd8daaaa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#translate-centres-services-main-modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='translate-centres-services-main-modal-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>de4aa73d-445b-4707-a957-70c1766f18a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>bcc9576b-2379-48c1-87db-ce49f1ca1849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>translate-centres-services-main-modal-title</value>
      <webElementGuid>fc356150-2ec6-45be-82a2-0f3d8009557b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Centres &amp; Services (Main)</value>
      <webElementGuid>480f9f8e-35b6-4998-84f4-e09b215f28ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;translate-centres-services-main-modal-title&quot;)</value>
      <webElementGuid>db42c655-6452-4f02-a3bd-16e741e54da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='translate-centres-services-main-modal-title']</value>
      <webElementGuid>e97b5d0a-c938-4cde-b4c3-5e9eef992707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_translate']/div/div/div[2]/h5</value>
      <webElementGuid>83baaf09-741b-4aac-8ded-2e37721f8514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sending item for translation'])[1]/following::h5[1]</value>
      <webElementGuid>1731aeca-5fcb-4e12-8633-730d0098af65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Close'])[1]/following::h5[1]</value>
      <webElementGuid>2b41410e-c4da-4e1a-b80a-9d9de3b4c4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[3]/preceding::h5[1]</value>
      <webElementGuid>c33ef110-0f76-43f1-a503-93a36d564429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Data'])[3]/preceding::h5[1]</value>
      <webElementGuid>60f82568-789d-4ef9-a7eb-0128fa66264b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/h5</value>
      <webElementGuid>3dda25a8-9635-44ef-93b9-b99e7610b08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'translate-centres-services-main-modal-title' and (text() = 'Centres &amp; Services (Main)' or . = 'Centres &amp; Services (Main)')]</value>
      <webElementGuid>5bb1b487-a012-4ed1-aec6-676cf8fa66c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
