<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Nothing selected_fa fa-plus</name>
   <tag></tag>
   <elementGuidId>372fddfa-a832-45ea-bdc7-edcf483340cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-specialty-checkboxes']/ul/li/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>43ac8e47-e188-441f-86c7-5fe35f8762aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>b094088a-043d-4f35-b405-5c69e35ba528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40e66506-bed8-4331-a88b-e04f39797260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-specialty-checkboxes&quot;)/ul[@class=&quot;gj-list gj-list-bootstrap&quot;]/li[@class=&quot;list-group-item&quot;]/div[1]/span[@class=&quot;gj-tree-font-awesome-expander&quot;]/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>7fc10d29-2f9a-490a-b6df-39752c466248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-specialty-checkboxes']/ul/li/div/span[2]/i</value>
      <webElementGuid>6233076d-cbe0-4901-af7f-907cc95c7e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>52ec3319-68f8-41d7-a83f-b9c9c6a451ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
