<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PageName-Edit</name>
   <tag></tag>
   <elementGuidId>33d215c4-2069-4704-ab97-27b5b54c4363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-input-page-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_edit-input-page-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>690aa183-1d11-45fb-bdec-175bc9e9c053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ddb7db5-da28-4e6d-8bc7-82915376c49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-page-name</value>
      <webElementGuid>6ad3503d-879d-4d97-bac0-20cb30f91d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-page-name</value>
      <webElementGuid>96c26d1a-0274-4bfa-ac76-b729bcfcd47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Page Name</value>
      <webElementGuid>7782aa5c-cc15-4df7-bab5-7b97e4dc1b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>itemURLPreDefined(this, 'edit')</value>
      <webElementGuid>3fe802ab-bceb-4316-a6cf-17a14e34b9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-input-page-name&quot;)</value>
      <webElementGuid>2c1f3ed5-b85b-436e-8594-16300c2a2949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_edit-input-page-name']</value>
      <webElementGuid>52630203-f6e4-41b1-8fef-26f4293b1e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>0d7eb331-e76c-4c8a-9953-145059d8156f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>5495c45e-2501-48ce-815c-2b385617337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_edit-input-page-name' and @id = 'centres_services_main_modal_edit-input-page-name' and @placeholder = 'Page Name']</value>
      <webElementGuid>3f7253fb-5350-42df-ae4a-6eb7ab0b4e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
