<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sort Order_Edit</name>
   <tag></tag>
   <elementGuidId>e420dc2e-ebc8-4c93-a3cb-33de7283931a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-input-sort-order</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_edit-input-sort-order']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6af28cb6-8a9e-4c92-86c1-c1822450e376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de478764-ecd0-43ae-850a-b0404646d425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-sort-order</value>
      <webElementGuid>882cb7a9-9638-4aae-a88a-f35bc06ec344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-sort-order</value>
      <webElementGuid>5c954f68-aa8a-4401-8be4-7ad61c81f69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Display Order</value>
      <webElementGuid>df7a0505-1b72-42d7-8ca9-b6447d0a59cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-input-sort-order&quot;)</value>
      <webElementGuid>0db052d5-8cef-4152-ae9f-af1f858d25d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_edit-input-sort-order']</value>
      <webElementGuid>190f705d-de21-4abd-b795-5e0388e5ec81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div[2]/div[4]/div/div/input</value>
      <webElementGuid>f31122a3-f282-44d6-9b6f-889d6b7ae8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div[2]/div[4]/div/div/input</value>
      <webElementGuid>ff7b74df-282b-401f-83b5-df25ee8f3d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_edit-input-sort-order' and @id = 'centres_services_main_modal_edit-input-sort-order' and @placeholder = 'Display Order']</value>
      <webElementGuid>7d19c6fe-66da-47f1-bf45-e9f2e62e503f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
