<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__H1 Display_Edit</name>
   <tag></tag>
   <elementGuidId>b117396a-096a-41e7-a77f-aa29f8a6ac60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-input-page-title-h1-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_edit-input-page-title-h1-display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47f14c8b-4549-451a-95ff-161d119f0ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d9b390d7-d8aa-4a56-b3dd-b2dbd4daea18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-page-title-h1-display</value>
      <webElementGuid>c65a8e2e-c30e-4dda-8e09-74ae9b15dedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-page-title-h1-display</value>
      <webElementGuid>b3a64ba5-0281-4b94-a80f-165966281928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Page Title (H1 Display)</value>
      <webElementGuid>74e5e9d4-21ce-475f-94c4-006a1b7da233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>5e1465c0-4140-4f77-9edf-28f93eb09d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>charsLengthCheck(this, 'edit', 'page-title-h1-display')</value>
      <webElementGuid>a2f66dbd-0fe7-4479-ae67-4540b30b2f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-input-page-title-h1-display&quot;)</value>
      <webElementGuid>9605b21b-ae27-4794-bc53-59c36d025242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_edit-input-page-title-h1-display']</value>
      <webElementGuid>877331c7-6a78-4892-a491-16ab5f821bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>eb861ccd-0f42-4e13-aab4-16d95cc7677c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>f79537cc-d0bd-4443-bd9e-f7f6d15b8b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_edit-input-page-title-h1-display' and @id = 'centres_services_main_modal_edit-input-page-title-h1-display' and @placeholder = 'Page Title (H1 Display)']</value>
      <webElementGuid>f415449b-4c0f-471b-a752-39a0a511eca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
