<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Main Image Alt Text</name>
   <tag></tag>
   <elementGuidId>dd00f7ce-85cf-47c7-9f81-62e706a20670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_add-input-main-image-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-input-main-image-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ae17caa-389e-4eac-aa1e-b11a995daf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a5b9adf4-ea54-4405-81bf-4ee48bbbe0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-main-image-text</value>
      <webElementGuid>55a25ab4-27ed-4097-aa78-9fadc2ee3265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-main-image-text</value>
      <webElementGuid>d2c4cf74-7c1e-44a5-8079-cde206b65080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Main Image Alt Text</value>
      <webElementGuid>0dd5b4a7-6423-4f98-a83b-14eb673a48f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-input-main-image-text&quot;)</value>
      <webElementGuid>2edfa431-910c-4125-bd9c-f893cb6cfe62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_add-input-main-image-text']</value>
      <webElementGuid>40c5e968-0d30-47c2-972f-600c8c05f246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div/div[3]/div/div/input</value>
      <webElementGuid>d3718453-5a12-47b1-bb37-e5eccdf09c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>b962b0db-5610-49aa-be3e-36373d28292f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_add-input-main-image-text' and @id = 'centres_services_main_modal_add-input-main-image-text' and @placeholder = 'Main Image Alt Text']</value>
      <webElementGuid>0d727a87-c41f-49c7-94bd-d70ff7c60b41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
