<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Additional CTA URL_Edit</name>
   <tag></tag>
   <elementGuidId>8bf32f03-4560-471c-bd6b-c6958b0d2587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-input-cta-url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_edit-input-cta-url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72cf7529-7efc-4ff6-bdbb-77477741f398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c7c473d-b70d-4d1e-b46c-6b8519646206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-cta-url</value>
      <webElementGuid>91df1ee6-88bc-4385-8c6b-05fdac94c77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-cta-url</value>
      <webElementGuid>c01d73a2-a637-4ea9-9006-4a719e58109f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional CTA URL</value>
      <webElementGuid>63644a13-bbe8-4aa9-8c93-1c1507b78bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-input-cta-url&quot;)</value>
      <webElementGuid>b999a050-be3b-4781-9d02-19b8a6245b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_edit-input-cta-url']</value>
      <webElementGuid>ee00e64e-2be7-4089-ab05-a6b6ede78b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div/div[2]/div/div[8]/div/div/input</value>
      <webElementGuid>3154f586-9a12-4bb1-b4dc-dec1ec3837fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div/div[2]/div/div[8]/div/div/input</value>
      <webElementGuid>54d24827-ef88-47ed-a45d-1f45961090af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_edit-input-cta-url' and @id = 'centres_services_main_modal_edit-input-cta-url' and @placeholder = 'Additional CTA URL']</value>
      <webElementGuid>7060da0f-9b64-4d62-8779-efec82c15fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
