<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__centres_services_main_modal_add-inpu_fdaa4b</name>
   <tag></tag>
   <elementGuidId>bc487c13-a2ba-4738-a714-72f2a64cfe91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_add-input-page-title-h1-display']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-input-page-title-h1-display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7ebe326-1c90-4683-9fc0-a8d420f0c67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3d90031a-a568-4a69-8c30-00807a32300a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-page-title-h1-display</value>
      <webElementGuid>a2819b94-f2be-4eee-a22b-168c97c48c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-page-title-h1-display</value>
      <webElementGuid>32e3cd49-820f-48ef-bb3f-d0554de5521c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Page Title (H1 Display)</value>
      <webElementGuid>bb37e30b-111f-4a60-b415-de6cafcbeb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>65aec832-3ade-4e4d-88af-c75463c912f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>charsLengthCheck(this, 'add', 'page-title-h1-display')</value>
      <webElementGuid>23d9a34d-5e6a-40ad-9737-f326ccaed88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-input-page-title-h1-display&quot;)</value>
      <webElementGuid>d778dbf2-fb9d-4e99-9d5b-6da1d0022d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_add-input-page-title-h1-display']</value>
      <webElementGuid>d2fc8284-ccc6-440c-9ef8-1219b1bf0239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>3b595522-6871-436a-96c9-c1fc1294260e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>97e32647-e0fa-4364-b895-f189592f6509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_add-input-page-title-h1-display' and @id = 'centres_services_main_modal_add-input-page-title-h1-display' and @placeholder = 'Page Title (H1 Display)']</value>
      <webElementGuid>6017d56c-6c17-45ef-b07d-1735925bec84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
