<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Page Name</name>
   <tag></tag>
   <elementGuidId>a9c88e87-806c-4961-af1a-c9ce55628334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_add-input-page-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-input-page-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6ece3b5-16cd-4f96-8df6-3a1d9c7f1b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e7e28dac-310f-405d-a98e-9415aeffa7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-page-name</value>
      <webElementGuid>e301f5f6-8a31-4ada-9330-85f9bd487b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-page-name</value>
      <webElementGuid>30643e08-6fb7-4ec8-92a5-30ca1038d0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Page Name</value>
      <webElementGuid>700d9f1b-a368-4dc9-a8c8-167220a4cfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>itemURLPreDefined(this, 'add')</value>
      <webElementGuid>ac8cc44c-cea4-4529-9efe-7d46f0197f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-input-page-name&quot;)</value>
      <webElementGuid>534db570-0c89-4924-8457-ba0bb6e054f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_add-input-page-name']</value>
      <webElementGuid>d489b3b8-88e8-42b7-ab3e-bec395b2c55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>b3a987f0-920e-41cc-b193-ad50cf619a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>6948118c-5e6c-4263-a557-5cbd008a42f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_add-input-page-name' and @id = 'centres_services_main_modal_add-input-page-name' and @placeholder = 'Page Name']</value>
      <webElementGuid>ec17d778-9a6a-414f-adc3-4869bc744438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
