<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse Image_entres_services_main_mod_74a45f</name>
   <tag></tag>
   <elementGuidId>01d0ccd9-a7e9-40bf-8747-949f32c82d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50b44acd-5efb-4a96-9c36-90aa05c454cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c18b38c-21ea-4710-a208-e868a158deb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN</value>
      <webElementGuid>4529defb-536c-4ff3-9ad4-dc5c185cb261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN</value>
      <webElementGuid>c493232b-bdb1-4839-aeab-506ba7472adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hospital Main Image Alt Text</value>
      <webElementGuid>bed77a40-a8ed-4e89-a09c-caf56f88232b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>metaDataFieldChange(this.value, 'hospitalMainImageAltText', 'KLTlN')</value>
      <webElementGuid>851740c8-8139-41c0-98d0-41a504e1e8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN&quot;)</value>
      <webElementGuid>6557965a-a377-49f5-a931-6634459d8266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN']</value>
      <webElementGuid>04078d2a-00e2-4030-b188-0ce7d13a7508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-KLTlN']/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>ae6e04ce-6ec9-4ec7-b165-2d8cc6571f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>22cdfb9c-b26f-4ed8-a067-cd7efa3bd6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN' and @id = 'entres_services_main_modal_add-input-hospital-main-image-alt-text-KLTlN' and @placeholder = 'Hospital Main Image Alt Text']</value>
      <webElementGuid>e9f36055-ee8a-489b-a93d-5fa984eaadac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
