<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display Find MP CTA_Edit</name>
   <tag></tag>
   <elementGuidId>fc82686a-d336-432f-8cda-8eeeb5b25a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-input-display-find-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_edit-input-display-find-cta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b863d72d-9173-4aa6-9427-cf70ef8e7970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>091de718-4aec-4ff6-9f6c-dcf3ca07bef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58ed6ab1-2898-437b-b6ce-b0cd04d91f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-display-find-cta</value>
      <webElementGuid>b60221f7-16eb-4437-a23b-91f5f0b0b8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-display-find-cta</value>
      <webElementGuid>5f5d3141-9685-4bf6-8563-0353bee71837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-input-display-find-cta&quot;)</value>
      <webElementGuid>4ffc2110-9527-4740-97c6-d7c0dc286477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_edit-input-display-find-cta']</value>
      <webElementGuid>5f6a2f9f-99b4-4076-a512-e36a3d0eedf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div/div[2]/div/div[6]/div/label/input</value>
      <webElementGuid>ebef2d36-a894-4916-9d8d-a9ab133b5fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div/div[2]/div/div[6]/div/label/input</value>
      <webElementGuid>25d9b909-39af-442c-8023-bb1c46f3ec17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'centres_services_main_modal_edit-input-display-find-cta' and @id = 'centres_services_main_modal_edit-input-display-find-cta']</value>
      <webElementGuid>275fa707-9596-4122-b134-53ce167170b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
