<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textarea-Summary</name>
   <tag></tag>
   <elementGuidId>39a0f3a1-fa9e-49d8-a4eb-0a3b94dcd327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='centres_services_main_modal_add-textarea-summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-textarea-summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14920951-0a1b-4962-9268-5d350e6d6cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textarea-allow-resize</value>
      <webElementGuid>a4d04983-1449-477e-a7f9-e894d3ad488b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-textarea-summary</value>
      <webElementGuid>8d9fc432-e364-4b87-b008-7b2f2f3a329f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-textarea-summary</value>
      <webElementGuid>33e5874a-f5f8-40ed-b8b3-8fac396a2cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a2d43c17-b60f-4df6-8176-a8aa2bf950ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>77e07dbe-9962-44e7-ab28-4cba326f1b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>charsLengthCheck(this, 'add', 'summary')</value>
      <webElementGuid>0f70e65d-0694-4a4a-b1e2-108e37812d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-textarea-summary&quot;)</value>
      <webElementGuid>44a45dd3-098a-4561-b6ac-097c84e77460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='centres_services_main_modal_add-textarea-summary']</value>
      <webElementGuid>e7a58ed3-58db-47a8-8f5d-1f2470f8a36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div[4]/div/div/textarea</value>
      <webElementGuid>21dcd0b1-535f-4d1b-8e90-f7d6be5408dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4a200ea9-295d-45ff-ab86-6f0d202b4797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'centres_services_main_modal_add-textarea-summary' and @id = 'centres_services_main_modal_add-textarea-summary' and @placeholder = 'Summary']</value>
      <webElementGuid>0cce0d07-f72f-4637-8530-a0f1578ec492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
