<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Main Image Alt Text_Edit</name>
   <tag></tag>
   <elementGuidId>99eb16c8-2bbc-41b6-af96-cd1726947372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-input-main-image-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_edit-input-main-image-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>778f43b6-4960-4fbf-a82b-19c309412450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3c0bb72-27ff-4141-b8d9-6169c3d80acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-main-image-text</value>
      <webElementGuid>177d2306-06b4-40d8-bb9e-387d71c90748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-input-main-image-text</value>
      <webElementGuid>942b71e4-5433-421e-9889-5ed5d204925f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Main Image Alt Text</value>
      <webElementGuid>4478003d-5944-459a-8fe6-e4ace1eea92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-input-main-image-text&quot;)</value>
      <webElementGuid>5cf14b40-6894-4e17-9d27-bda1ca06ce02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_edit-input-main-image-text']</value>
      <webElementGuid>4754f1d8-993a-4065-b100-3f3825cbd2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div/div/div[3]/div/div/input</value>
      <webElementGuid>c2970ce3-956d-4dc1-b82d-1d619a57f162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>5c60f73d-a995-4246-b339-e3a1c4c1a0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_edit-input-main-image-text' and @id = 'centres_services_main_modal_edit-input-main-image-text' and @placeholder = 'Main Image Alt Text']</value>
      <webElementGuid>7279dba4-583c-4b0d-8582-327ea42d59d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
