<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Additional CTA Label_centres_services_ccf2cd</name>
   <tag></tag>
   <elementGuidId>d6098e10-0738-4ca8-a395-d01915916e07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_add-input-cta-url']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-input-cta-url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a4c8317-19a5-4cf0-9360-daf0f2767565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f174844b-acb0-4f53-b7e2-b2f4473720cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-cta-url</value>
      <webElementGuid>04cf20b7-9c8f-4d3b-9ef0-20ee8470a6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-cta-url</value>
      <webElementGuid>9f9b69d8-60c9-4497-ac16-50a83a275d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional CTA URL</value>
      <webElementGuid>81a211ff-1ba7-4b99-a764-4390d5929a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-input-cta-url&quot;)</value>
      <webElementGuid>936895a7-b14f-4964-9697-1bf1eb2525ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_add-input-cta-url']</value>
      <webElementGuid>f265a0e0-f0c0-40f7-a512-9d6bc39ffcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div[8]/div/div/input</value>
      <webElementGuid>b308c872-94cf-46fb-adfa-904a4bb77bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>929bf7dd-9d15-467e-ac78-e3a32fe9360b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'centres_services_main_modal_add-input-cta-url' and @id = 'centres_services_main_modal_add-input-cta-url' and @placeholder = 'Additional CTA URL']</value>
      <webElementGuid>f5ee5e45-799a-43ea-a105-bba837989700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
