<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display Enquiry CTA-CheckList</name>
   <tag></tag>
   <elementGuidId>500c91d6-105b-4319-be45-48ecd025a4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main_modal_add-input-display-enquiry-cta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-input-display-enquiry-cta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a75b9d5-5194-4ab6-bae2-0bbe932f9863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7194f0bf-ccca-4670-96de-17dd62673136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5bac37dd-ed7c-4a12-b4f6-221ef2380d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-display-enquiry-cta</value>
      <webElementGuid>c5174463-9fea-4347-9bb7-4593e3cccc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-input-display-enquiry-cta</value>
      <webElementGuid>5ee348ec-ef44-4d8f-aaa5-52cfce014706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-input-display-enquiry-cta&quot;)</value>
      <webElementGuid>671ce0a2-9702-47e9-ad9f-d1d8a1ff7f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main_modal_add-input-display-enquiry-cta']</value>
      <webElementGuid>5bc13b39-6870-4897-86f9-11e112228a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div[5]/div/label/input</value>
      <webElementGuid>f832c10c-e3dc-4c9f-8f9c-b2d4c8c2143d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/input</value>
      <webElementGuid>cf976c79-e8d1-4200-8954-f22b339392ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'centres_services_main_modal_add-input-display-enquiry-cta' and @id = 'centres_services_main_modal_add-input-display-enquiry-cta']</value>
      <webElementGuid>114d17fc-00e6-443a-a4e1-879ce9de0251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
