<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_centres_services_main-input-search</name>
   <tag></tag>
   <elementGuidId>e4022606-3815-462c-b338-bf9fe17ad94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='centres_services_main-input-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main-input-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7386d024-f232-47ef-8198-da5af9d576ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c31e12f-ed47-4ab2-9c26-208d79d194f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input</value>
      <webElementGuid>6f37ca39-5a59-45b0-ba88-86433a8c28bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main-input-search</value>
      <webElementGuid>fcc5fba2-e507-4456-8466-d808a4696bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main-input-search</value>
      <webElementGuid>bed59729-87d2-43eb-adc7-b829877b0364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main-input-search&quot;)</value>
      <webElementGuid>e538af5e-f291-44a6-af5c-147d55374d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='centres_services_main-input-search']</value>
      <webElementGuid>5e4b6480-9cdd-4481-9b89-1e601d95fc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>69a59c6b-efc0-4fee-9fc5-d736806c9b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'centres_services_main-input-search' and @name = 'centres_services_main-input-search']</value>
      <webElementGuid>60575b8a-946e-4b0f-9d17-63eacc2edc3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
