<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>publish_this-perent</name>
   <tag></tag>
   <elementGuidId>ba96db0b-bcf7-4d36-916b-fd141e484dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='centres_services_main_modal_translate-select-language-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_translate-select-language-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5885ffaa-f960-4e64-96b8-f8cf43918acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84028f55-7e37-461c-b2ca-6c5c8f782ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ignore-trigger translation-language-select</value>
      <webElementGuid>12e07c68-af5b-4a17-8f3f-a3de36fa87de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_translate-select-language-code</value>
      <webElementGuid>3d7aea58-16e0-4960-bb62-c1c644357b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_translate-select-language-code</value>
      <webElementGuid>d1d9d9c1-33b1-45f4-9278-760d1c49a534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Language Code</value>
      <webElementGuid>fc88cfb0-ed4c-4d21-882d-883201320c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bahasa IndonesiaChineseEnglishVietnamese</value>
      <webElementGuid>50839761-9a36-4396-a21f-bd8475424613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_translate-select-language-code&quot;)</value>
      <webElementGuid>f148047b-38af-411e-8d36-dac4c3f69241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='centres_services_main_modal_translate-select-language-code']</value>
      <webElementGuid>e9c9e77a-c4bb-459b-b21f-6e92a2c48697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_translate']/div/div/div[2]/div/div/select</value>
      <webElementGuid>6bbc2372-c46d-4bbe-a156-1905cce16982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centres &amp; Services (Main)'])[5]/following::select[1]</value>
      <webElementGuid>d7d76e70-1768-4fca-92b6-602932482d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sending item for translation'])[1]/following::select[1]</value>
      <webElementGuid>194e1709-c9d4-41da-a8ec-4e8b1b50dfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[3]/preceding::select[1]</value>
      <webElementGuid>d9a9b755-d393-4bfc-bb20-86e9a2304270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Data'])[3]/preceding::select[1]</value>
      <webElementGuid>ad4c3c89-91ab-4c56-9a8a-5d9a81ab92c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/select</value>
      <webElementGuid>959856d2-7ca6-4055-b906-9af3edb1a5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @name = 'centres_services_main_modal_translate-select-language-code' and @id = 'centres_services_main_modal_translate-select-language-code' and @placeholder = 'Language Code' and (text() = 'Bahasa IndonesiaChineseEnglishVietnamese' or . = 'Bahasa IndonesiaChineseEnglishVietnamese')]</value>
      <webElementGuid>7463a91f-342a-4300-b7bf-e1ac42cd844b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
