<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language_published_Detail</name>
   <tag></tag>
   <elementGuidId>fbf9ecdb-a436-484b-aa51-cd86982f7e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='centres_services_main_modal_translate-select-language-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_translate-select-language-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8ccd80bd-071e-4f25-a4ed-58a8b78d6188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81ca5242-7c8f-4163-91a1-c8ef2a85b9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ignore-trigger translation-language-select</value>
      <webElementGuid>aeb1f158-5705-4bfd-9c56-01028f571b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_translate-select-language-code</value>
      <webElementGuid>7ae22242-c062-4c8a-a99b-7c31f2ff5326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_translate-select-language-code</value>
      <webElementGuid>01541cca-ad68-4006-a923-9624b45b7dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Language Code</value>
      <webElementGuid>4068db8a-d52f-44b6-85b0-32ad594fd97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bahasa IndonesiaChineseEnglishVietnamese</value>
      <webElementGuid>90202ec5-16e6-4620-bd34-c80ea28812c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_translate-select-language-code&quot;)</value>
      <webElementGuid>27b47380-2c85-4f66-a5f2-15e50f378434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='centres_services_main_modal_translate-select-language-code']</value>
      <webElementGuid>782f2766-c7e5-40a6-a934-27fd9927c28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_translate']/div/div/div[2]/div/div/select</value>
      <webElementGuid>761471a8-4f57-416c-a0d3-e2b1113df881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centres &amp; Services (Main)'])[5]/following::select[1]</value>
      <webElementGuid>8b2e7a36-5883-4797-906b-ddb8438d6799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sending item for translation'])[1]/following::select[1]</value>
      <webElementGuid>de6cea17-cbcd-4e31-91a3-5b46ed14b4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[3]/preceding::select[1]</value>
      <webElementGuid>5db84f8e-9df0-49bf-962e-f5256b96e24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Data'])[3]/preceding::select[1]</value>
      <webElementGuid>81e1941e-288f-4267-b63a-14ab819e5e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/select</value>
      <webElementGuid>71a06b26-8df9-44ad-8421-f9d5b829a661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @name = 'centres_services_main_modal_translate-select-language-code' and @id = 'centres_services_main_modal_translate-select-language-code' and @placeholder = 'Language Code' and (text() = 'Bahasa IndonesiaChineseEnglishVietnamese' or . = 'Bahasa IndonesiaChineseEnglishVietnamese')]</value>
      <webElementGuid>cae13b75-290e-4b24-9721-0c46b5ed2b5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
