<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Clinical EmbryologyMedical AdvisorNu_88852e</name>
   <tag></tag>
   <elementGuidId>f79a8228-763f-49d3-9a2c-682dc6943cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='centres_services_main_modal_add-select-service-provider-types']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-select-service-provider-types</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>954fd3c4-914d-4e66-98f1-84b70f45e000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamic-picker service-provider-types-select ignore-trigger</value>
      <webElementGuid>7b0314d3-93d1-4156-a437-d82ce6d357c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-select-service-provider-types</value>
      <webElementGuid>c82f3843-2f40-487e-970b-816b1009e558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-select-service-provider-types</value>
      <webElementGuid>981a165f-9122-4a87-8556-e24737ce7843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>df03caf8-98aa-45b1-bdf8-79b3e03a83d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fdb206a1-cc9b-48ab-abf5-d5bffcbe3e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>6efd1885-5074-4c44-82a0-4db8ff92a143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinical EmbryologyMedical AdvisorNutrition and DieteticsOccupational TherapyPhysiotherapyPodiatryPsychologySpeech Therapy</value>
      <webElementGuid>18dd8f1c-3b1c-4c71-8093-cdd28cb62642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-select-service-provider-types&quot;)</value>
      <webElementGuid>32bc643b-10a4-4228-bb79-34e71fb6d090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='centres_services_main_modal_add-select-service-provider-types']</value>
      <webElementGuid>db5a25f0-1e07-4c64-a550-62bb372d1e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div[2]/div[3]/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>0a6e22ac-742d-4e5c-8080-63db4b3905ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Provider Types'])[3]/following::select[1]</value>
      <webElementGuid>2253ade1-6a8d-47c0-85f4-089a02701403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/following::select[1]</value>
      <webElementGuid>4315c7f8-eca1-4dd1-b048-cf271d77f8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing selected'])[2]/preceding::select[1]</value>
      <webElementGuid>b8a63612-de9a-49bf-98a3-a1c6c9cff1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::select[1]</value>
      <webElementGuid>27d57c62-02cf-42e5-930f-913fd95b032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>b3fce18d-3efd-4e1b-89a0-8fc057562e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'centres_services_main_modal_add-select-service-provider-types' and @id = 'centres_services_main_modal_add-select-service-provider-types' and (text() = 'Clinical EmbryologyMedical AdvisorNutrition and DieteticsOccupational TherapyPhysiotherapyPodiatryPsychologySpeech Therapy' or . = 'Clinical EmbryologyMedical AdvisorNutrition and DieteticsOccupational TherapyPhysiotherapyPodiatryPsychologySpeech Therapy')]</value>
      <webElementGuid>3ca203ac-ec77-4809-9b68-f6732d7f5349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
