<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Abdul Kader AnsariAlefia VasanwalaAl_c97580</name>
   <tag></tag>
   <elementGuidId>ba42590a-8f94-4a06-96b5-62e3cd7c2cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='medical-professional-ahp-listing-mode-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#medical-professional-ahp-listing-mode-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59392478-0e8c-41aa-8661-aaeec5c9b921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamic-picker-2 medical-professional-select</value>
      <webElementGuid>055289c2-7432-4b59-9c85-23185f4b75f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>medical-professional-ahp-listing-mode-select</value>
      <webElementGuid>a244f89e-1326-4d8f-8e1a-b9c52d846d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>medical-professional-ahp</value>
      <webElementGuid>3fd446c7-f14b-470f-9ecf-06b80a175d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>290362bb-fc4e-4664-9233-6c6c3b893255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1da266c4-bf98-47c8-b9bd-73a174ec4029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>22ce958e-7112-426e-a460-062e6c440458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abdul Kader AnsariAlefia VasanwalaAlizul Bin AhmedChan Min KyiChandran TamilselvanChaw Chaw SuChiang Seng MaryChua ShuzhenCorey Michael Cheng Zai LiangDiane SetoGrace YantiHo Chin Fui WilliamHo Huiqi KiraIrene AlbanJanine ChengJavier Edward MendozaJenette YeeJennifer ShimJoy LimKaw Jon KeenKe Bing-RuKhoo Hooi Meng PamelaKyaw Soe LyinLee Wing KuenLim Han Rong HannielLim Wei JunLoh Chian Poo DavidLooi Bee HongLouis YapLow Han KeatMurugappan SaminathanNant Mya Mya Thet LuciaNatalie GohNg Jing Yi RaneNg Lai ChengNg Sooi Teng RachelNg Xinyi JoleneNurul Natasha Binte Mohamed NasirPang Hui LiPhyo Thandar Htay HelenRachel TayRinku DeviS G SivakumaarSahayog SahaySim Hui Zhi TaniaSiti Aisyah EilyaasTan Hui ShiTan Hui YongTan Si Wei RaechelleTan Yen LengTan Ying XinTay Seyang AlanTay Wee KokTeo Lin-Li DaphneWang Yu HuiWei Lisi ArabelleWong Hui MeiWong Seow Ping FlorenceYap Poh FangYau Heen OnnZin Minn Ei</value>
      <webElementGuid>46c04c77-febe-4ca9-922d-c261c772c2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-medical-professional-ahp-listing-mode&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-12 col-xs-12 form-container&quot;]/div[@class=&quot;dropdown bootstrap-select show-tick dynamic-picker-2 medical-professional-select dropup show&quot;]/select[@id=&quot;medical-professional-ahp-listing-mode-select&quot;]</value>
      <webElementGuid>ea60a134-6bb7-4054-a6b4-b36531f18669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='medical-professional-ahp-listing-mode-select']</value>
      <webElementGuid>737803f3-31a4-41c3-983f-2763fc4d596d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-medical-professional-ahp-listing-mode']/div/div/div/select</value>
      <webElementGuid>f1f0c83c-3ca9-4d03-a81c-7b0f82434344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Professional'])[4]/following::select[1]</value>
      <webElementGuid>6989c2d1-499c-41cb-b022-137dfc9cca35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>4e60bdbe-c5df-45d6-abb6-146a084ed19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing selected'])[3]/preceding::select[1]</value>
      <webElementGuid>ed824961-aff7-4c05-94cc-eb1445d4117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[4]/preceding::select[1]</value>
      <webElementGuid>bc990c06-d80e-40d7-8d44-551b75aa1e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/select</value>
      <webElementGuid>2db7e9e5-a00e-4975-b7e7-f170effc1c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'medical-professional-ahp-listing-mode-select' and @name = 'medical-professional-ahp' and (text() = 'Abdul Kader AnsariAlefia VasanwalaAlizul Bin AhmedChan Min KyiChandran TamilselvanChaw Chaw SuChiang Seng MaryChua ShuzhenCorey Michael Cheng Zai LiangDiane SetoGrace YantiHo Chin Fui WilliamHo Huiqi KiraIrene AlbanJanine ChengJavier Edward MendozaJenette YeeJennifer ShimJoy LimKaw Jon KeenKe Bing-RuKhoo Hooi Meng PamelaKyaw Soe LyinLee Wing KuenLim Han Rong HannielLim Wei JunLoh Chian Poo DavidLooi Bee HongLouis YapLow Han KeatMurugappan SaminathanNant Mya Mya Thet LuciaNatalie GohNg Jing Yi RaneNg Lai ChengNg Sooi Teng RachelNg Xinyi JoleneNurul Natasha Binte Mohamed NasirPang Hui LiPhyo Thandar Htay HelenRachel TayRinku DeviS G SivakumaarSahayog SahaySim Hui Zhi TaniaSiti Aisyah EilyaasTan Hui ShiTan Hui YongTan Si Wei RaechelleTan Yen LengTan Ying XinTay Seyang AlanTay Wee KokTeo Lin-Li DaphneWang Yu HuiWei Lisi ArabelleWong Hui MeiWong Seow Ping FlorenceYap Poh FangYau Heen OnnZin Minn Ei' or . = 'Abdul Kader AnsariAlefia VasanwalaAlizul Bin AhmedChan Min KyiChandran TamilselvanChaw Chaw SuChiang Seng MaryChua ShuzhenCorey Michael Cheng Zai LiangDiane SetoGrace YantiHo Chin Fui WilliamHo Huiqi KiraIrene AlbanJanine ChengJavier Edward MendozaJenette YeeJennifer ShimJoy LimKaw Jon KeenKe Bing-RuKhoo Hooi Meng PamelaKyaw Soe LyinLee Wing KuenLim Han Rong HannielLim Wei JunLoh Chian Poo DavidLooi Bee HongLouis YapLow Han KeatMurugappan SaminathanNant Mya Mya Thet LuciaNatalie GohNg Jing Yi RaneNg Lai ChengNg Sooi Teng RachelNg Xinyi JoleneNurul Natasha Binte Mohamed NasirPang Hui LiPhyo Thandar Htay HelenRachel TayRinku DeviS G SivakumaarSahayog SahaySim Hui Zhi TaniaSiti Aisyah EilyaasTan Hui ShiTan Hui YongTan Si Wei RaechelleTan Yen LengTan Ying XinTay Seyang AlanTay Wee KokTeo Lin-Li DaphneWang Yu HuiWei Lisi ArabelleWong Hui MeiWong Seow Ping FlorenceYap Poh FangYau Heen OnnZin Minn Ei')]</value>
      <webElementGuid>e9225b0d-4af0-4edf-b966-262ebc71a831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
