<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Clinical EmbryologyMedical AdvisorNu_88852e</name>
   <tag></tag>
   <elementGuidId>f79a8228-763f-49d3-9a2c-682dc6943cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-select-service-provider-types</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='centres_services_main_modal_add-select-service-provider-types']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad6c4a0d-435c-4fcf-aae3-92aefd481227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamic-picker service-provider-types-select ignore-trigger</value>
      <webElementGuid>a650a7b3-d314-4ea4-8e2c-4cc08a4f3cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-select-service-provider-types</value>
      <webElementGuid>01f8fddd-4a3f-4137-ada7-c1e6486fa72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-select-service-provider-types</value>
      <webElementGuid>f9e59fc6-0e95-4e19-bf88-6bd8f0832baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>cc49181b-26d0-4a47-8003-68c1d2342909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7509445f-deda-4999-a70c-c101328252e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>184f1da6-0e50-4b84-8911-7e571276baaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinical EmbryologyMedical AdvisorNutrition and DieteticsOccupational TherapyPhysiotherapyPodiatryPsychologySpeech Therapy</value>
      <webElementGuid>037ae5d6-718b-4bc2-ab99-e09f0988504c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-select-service-provider-types&quot;)</value>
      <webElementGuid>bf6316c8-ad08-4439-8dba-14e01ba2e7b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='centres_services_main_modal_add-select-service-provider-types']</value>
      <webElementGuid>455d3f76-c530-41a7-b7ba-b3d8487bc0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div[2]/div[3]/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>a8c37c3a-a65b-435f-b8f2-a6a79a1586f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Provider Types'])[3]/following::select[1]</value>
      <webElementGuid>e2a15d14-8ab1-4808-8903-503c40445247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/following::select[1]</value>
      <webElementGuid>8640824b-d2cf-49a4-98a3-9a649e8fd385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing selected'])[3]/preceding::select[1]</value>
      <webElementGuid>77b062bf-b53e-470b-9e62-c63777ed7e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::select[1]</value>
      <webElementGuid>b6fe7bca-4ec4-4e71-bf51-b9307fce6e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>1434a383-12a6-4e7a-8a72-9c261c022c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'centres_services_main_modal_add-select-service-provider-types' and @id = 'centres_services_main_modal_add-select-service-provider-types' and (text() = 'Clinical EmbryologyMedical AdvisorNutrition and DieteticsOccupational TherapyPhysiotherapyPodiatryPsychologySpeech Therapy' or . = 'Clinical EmbryologyMedical AdvisorNutrition and DieteticsOccupational TherapyPhysiotherapyPodiatryPsychologySpeech Therapy')]</value>
      <webElementGuid>8b8b2d09-b444-4d6a-9269-4ad93deb08b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing selected'])[2]/preceding::select[1]</value>
      <webElementGuid>b8a63612-de9a-49bf-98a3-a1c6c9cff1b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
