<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_close_Detail-page</name>
   <tag></tag>
   <elementGuidId>58df86df-54be-45ab-b08d-40026798599e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_translate-button-close > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='centres_services_main_modal_translate-button-close']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95467dba-8799-45c5-88d9-467129d9e8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>471d3fe8-ba62-4065-a941-90619e8a1e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>ef68094f-a19c-4668-9770-c89251ec9ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_translate-button-close&quot;)/span[1]</value>
      <webElementGuid>a8515263-4ab2-4049-98d0-5b6cf3510c37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='centres_services_main_modal_translate-button-close']/span</value>
      <webElementGuid>c70c9682-fcaa-46c8-bc14-5c931f014c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centres &amp; Services (Main)'])[5]/following::span[1]</value>
      <webElementGuid>d988adca-22f4-449e-9d55-9ac15e0704b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sending item for translation'])[1]/following::span[1]</value>
      <webElementGuid>09b9ab1d-6fff-4bf3-b718-bea13b52c7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[3]/preceding::span[1]</value>
      <webElementGuid>58d9c430-f997-43a4-9c1d-8f16736e79df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Data'])[3]/preceding::span[1]</value>
      <webElementGuid>c2fd0825-eb9f-43d1-850d-d0ae26207b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/button/span</value>
      <webElementGuid>23f79e17-c84e-449f-8120-e31999357b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>5cb1a1a0-0156-479f-9a0d-c6888f92fdfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
