<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Abdul Razakjr Bin Omar</name>
   <tag></tag>
   <elementGuidId>5abbe320-0dc8-4402-a2ea-5bd1dbcb4e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-0 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-0']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a242198-9ae4-4a33-ae8c-6b2ab5dd0b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec48bd81-e0b1-48cf-a849-f97f6ae4e392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abdul Razakjr Bin Omar</value>
      <webElementGuid>0f2f60ce-fb97-4ebf-a38a-b44674f924f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-0&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>d050aaf4-7267-4f68-9064-b93fa6e4d078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-0']/span[2]</value>
      <webElementGuid>8b67f9f9-be5d-4643-91eb-5a690bdd1bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[3]/following::span[2]</value>
      <webElementGuid>c6bdeed5-8a81-42d0-8d98-1eea349cec5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[3]/following::span[2]</value>
      <webElementGuid>dd384160-7cb1-427c-b883-09dde1c775d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adrian Siew Ming Saurajen'])[2]/preceding::span[2]</value>
      <webElementGuid>e8dc311e-7183-4715-b13a-ce7476091c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agasthian T'])[2]/preceding::span[4]</value>
      <webElementGuid>eb1b9121-2792-4766-a84c-d8cd208421c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/ul/li/a/span[2]</value>
      <webElementGuid>980d71ed-2c49-4cce-996e-64da61c82373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Abdul Razakjr Bin Omar' or . = 'Abdul Razakjr Bin Omar')]</value>
      <webElementGuid>2dcd8271-5d37-413e-a668-f94a3c628c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
