<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Clinical Embryology</name>
   <tag></tag>
   <elementGuidId>fbf96e6a-435f-44fb-b4f9-3b54fc5cfb85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-8-0']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43713ae7-d863-49f8-a7b1-09e2885f9b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6b387da-9f72-49af-aecf-210e29500f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinical Embryology</value>
      <webElementGuid>8e3bc2e7-7325-47dc-9e6d-7e68025f34b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-8-0&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>51ffdf95-4cf6-4e44-8025-aae315bc2a6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-8-0']/span[2]</value>
      <webElementGuid>fdd8ade7-0fd6-44c5-9949-9a39e347f1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[2]/following::span[2]</value>
      <webElementGuid>50d3a517-7aaf-48af-bbb6-884de5fbbadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/following::span[2]</value>
      <webElementGuid>c2725372-26e8-446f-9cf4-1ce019c31423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Advisor'])[2]/preceding::span[2]</value>
      <webElementGuid>75713ef0-b005-4316-8366-334d87c37fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nutrition and Dietetics'])[2]/preceding::span[4]</value>
      <webElementGuid>43e05e1f-3c49-4637-bd08-594208c6d944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span[2]</value>
      <webElementGuid>eafc9c63-dfa9-4b7f-a85f-a6895b7b204f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Clinical Embryology' or . = 'Clinical Embryology')]</value>
      <webElementGuid>865e9830-1d3b-41c7-be2b-6443e6adace3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
