<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__centres_services_main_modal_add-t_3e4212</name>
   <tag></tag>
   <elementGuidId>9e05422e-ca8c-4129-85c5-ddc6f65b085b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='centres_services_main_modal_add-textarea-summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_add-textarea-summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>71f47ac2-ef8c-4d31-abd8-add84bf57e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textarea-allow-resize</value>
      <webElementGuid>64e27255-1bd6-491a-9a82-4a01a7868422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-textarea-summary</value>
      <webElementGuid>6d8f2606-e401-4a2b-915a-b0693620a030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_add-textarea-summary</value>
      <webElementGuid>7f279241-85d8-4aac-8320-a2d46b0c0fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>debdfe25-b489-4fb8-a1fd-f115f1bc92c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>c824e932-259a-4e3e-856d-43dffff04100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>charsLengthCheck(this, 'add', 'summary')</value>
      <webElementGuid>e4f1e3a4-c1b6-45d8-b1e3-b019fb0ef265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_add-textarea-summary&quot;)</value>
      <webElementGuid>0255db73-48ee-407d-a032-66d170dff615</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='centres_services_main_modal_add-textarea-summary']</value>
      <webElementGuid>6e2b1ad3-66fc-45f8-b60f-a8d7e17fdfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_add-basic-information-tab-content']/div/div[2]/div/div[4]/div/div/textarea</value>
      <webElementGuid>9e227e96-2cfb-4238-9827-09992e459e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>63b0898c-c88f-47f6-9f1f-bf3e87514fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'centres_services_main_modal_add-textarea-summary' and @id = 'centres_services_main_modal_add-textarea-summary' and @placeholder = 'Summary']</value>
      <webElementGuid>d114e64e-a448-47c8-8d0a-8bbedcff7f9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
