<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Summary_Edit</name>
   <tag></tag>
   <elementGuidId>32bc9b54-cf46-4949-9d35-ca7218e24f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#centres_services_main_modal_edit-textarea-summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='centres_services_main_modal_edit-textarea-summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>daadb9ce-d206-4b3a-ab44-482cbe2b66e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textarea-allow-resize</value>
      <webElementGuid>d171532e-e1c7-4791-8e2f-686e05c89dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-textarea-summary</value>
      <webElementGuid>3c1f3f6f-943b-435d-86a6-d180e322a37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>centres_services_main_modal_edit-textarea-summary</value>
      <webElementGuid>1fc895d7-47bb-47ff-8dc6-9bcd8cc37299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b543c665-06b3-439d-b6b7-a5f9541e7d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>d0e5f693-1eef-4c31-9ef2-dfc3ef5b9927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>charsLengthCheck(this, 'edit', 'summary')</value>
      <webElementGuid>720a76f3-dbfd-4923-ba49-dad0bcc9a3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;centres_services_main_modal_edit-textarea-summary&quot;)</value>
      <webElementGuid>3b8aa6c0-7c84-4dad-a4fc-1500f4e00d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='centres_services_main_modal_edit-textarea-summary']</value>
      <webElementGuid>61ff5261-48c0-4745-a3a6-54fc1fd0b6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='centres_services_main_modal_edit-basic-information-tab-content']/div/div[2]/div/div[4]/div/div/textarea</value>
      <webElementGuid>2127f761-d84e-4cc6-8c8b-b7032cc9677e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div/div/div/div/div/div[2]/div/div[4]/div/div/textarea</value>
      <webElementGuid>b1cb7fc9-3942-4ea8-ae8d-bfaff991d007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'centres_services_main_modal_edit-textarea-summary' and @id = 'centres_services_main_modal_edit-textarea-summary' and @placeholder = 'Summary']</value>
      <webElementGuid>90e94275-aa9e-4555-8748-8840ddce60b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
